In [186]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

# Data preparation & Cleaning
 This file aims to prepare data for analysis

## Data used:

 When adding new data, I will be adding it here. If explanation is need about the data, it will be provided here.

### 1. Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org/RPP](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))

The selected residential property prices data set shows the most representative property price indicator for each country. For most economies, this series refers to the whole country and covers the entire market: all property types, both new and existing vintages.  
**Type Variable**: Dependent Variable (**Y**)

### 2. The central Banks policy rates - 2010-2025, monthly ([Bis.data.org/CBPR](https://data.bis.org/topics/CBPOL/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DM%255EYEAR%3D2010%257C2011%257C2012%257C2013%257C2014%257C2018%257C2016%257C2017%257C2015%257C2019%257C2020%257C2021%257C2022%257C2025%257C2024%257C2023))

The BIS central bank policy rates data set tracks the evolution of policy rates across the world. The policy rate is an important instrument used by central banks to implement their monetary policy.  
**Type Variable**: Independent Variable (**$X_1$**)

### 3. Consumer prices - 2010-2025, Changes over one year, ([Bis.data.org/CPI](https://data.bis.org/topics/CPI/data?data_view=table&rows=REF_AREA&cols=FREQ%7CTIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DA%257CM%255EUNIT_MEASURE%3D771%255EYEAR%3D2010%257C2011%257C2012%257C2013%257C2014%257C2018%257C2017%257C2016%257C2015%257C2019%257C2020%257C2021%257C2022%257C2023%257C2024%257C2025))

The consumer price index data set contains long series that track the overall change in the prices of goods and services purchased by households. Consumer price indices are a key macroeconomic indicator, for instance to measure inflation and assess purchasing power over time.

### 4. Real GDP Growth - 2010-2025, YoY ([OECD](https://data-explorer.oecd.org/vis?df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_NAMAIN1%40DF_QNA_EXPENDITURE_GROWTH_OECD&df[ag]=OECD.SDD.NAD&df[vs]=1.1&dq=Q..AUS%2BAUT%2BBEL%2BCAN%2BCHL%2BCOL%2BCRI%2BCZE%2BDNK%2BEST%2BFIN%2BFRA%2BDEU%2BGRC%2BHUN%2BISL%2BIRL%2BISR%2BITA%2BJPN%2BKOR%2BLVA%2BLTU%2BLUX%2BMEX%2BNLD%2BNZL%2BNOR%2BPOL%2BPRT%2BSVK%2BSVN%2BESP%2BSWE%2BCHE%2BTUR%2BGBR%2BUSA%2BARG%2BBRA%2BCHN%2BIND%2BIDN%2BRUS%2BSAU%2BZAF...B1GQ......G1.&ly[cl]=TIME_PERIOD&ly[rw]=REF_AREA&to[TIME_PERIOD]=false&vw=tb&lc=en&pg=0&pd=2010-Q1%2C2025-Q4))

This table presents Gross Domestic Product (GDP) and its main components according to the expenditure approach. Data is presented as growth rates.  
**Type Variable**: Control Variable (**$X_2$**)

### 5. Monthly Unemployment Rates - 2010-2025, ([OECD](https://data-explorer.oecd.org/vis?lc=en&tm=unemployement&pg=0&snb=87&vw=tb&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_LFS%40DF_IALFS_UNE_M&df[ag]=OECD.SDD.TPS&df[vs]=1.0&dq=AUS%2BAUT%2BBEL%2BCAN%2BCHL%2BCOL%2BCRI%2BCZE%2BDNK%2BEST%2BFIN%2BFRA%2BDEU%2BGRC%2BHUN%2BISL%2BIRL%2BISR%2BITA%2BJPN%2BKOR%2BLVA%2BLTU%2BLUX%2BMEX%2BNLD%2BNZL%2BNOR%2BPOL%2BPRT%2BSVK%2BSVN%2BESP%2BSWE%2BCHE%2BTUR%2BGBR%2BUSA%2BBGR%2BHRV%2BROU..._Z.Y._T.Y_GE15..Q&pd=2010-Q1%2C2025-Q4&to[TIME_PERIOD]=false))

The infra-annual data flow on the monthly unemployment rate is a subset of the infra-annual labor statistics database, which contains quarterly statistics 
**Type Variable**: Control Variable (**$X_3$**)

# Data 1: Residential property prices - index , real(adjusted for inflation)

In [187]:
HPI_raw = pd.read_csv("raw_data/Housing_price_index_real.csv.csv", skiprows=7)
HPI = HPI_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']].copy()
HPI.columns = ['Country_Raw', 'Quarter', 'Real_HPI']

In [188]:
HPI

                                   Country_Raw     Quarter  Real_HPI
0     4T:Emerging market economies (aggregate)  2007-12-31   95.7745
1     4T:Emerging market economies (aggregate)  2008-03-31   95.0590
2     4T:Emerging market economies (aggregate)  2008-06-30   95.3475
3     4T:Emerging market economies (aggregate)  2008-09-30   95.6345
4     4T:Emerging market economies (aggregate)  2008-12-31   95.3757
...                                        ...         ...       ...
5750                           ZA:South Africa  2024-12-31   87.9349
5751                           ZA:South Africa  2025-03-31   87.9561
5752                           ZA:South Africa  2025-06-30   88.0077
5753                           ZA:South Africa  2025-09-30   88.3881
5754                           ZA:South Africa  2025-12-31   89.4681

[5755 rows x 3 columns]

I see there are aggregate data I do not need, so I will use a mask

In [189]:
mask = HPI['Country_Raw'].str.contains('aggregate|economies|World|area', case=False)
HPI = HPI[~mask].copy()

In [190]:
HPI

          Country_Raw     Quarter  Real_HPI
144        AT:Austria  2000-03-31   98.2843
145        AT:Austria  2000-06-30   95.9464
146        AT:Austria  2000-09-30   93.7325
147        AT:Austria  2000-12-31   92.7328
148        AT:Austria  2001-03-31   96.5591
...               ...         ...       ...
5750  ZA:South Africa  2024-12-31   87.9349
5751  ZA:South Africa  2025-03-31   87.9561
5752  ZA:South Africa  2025-06-30   88.0077
5753  ZA:South Africa  2025-09-30   88.3881
5754  ZA:South Africa  2025-12-31   89.4681

[5436 rows x 3 columns]

Now, to remove the country code codes

In [191]:
HPI['Country'] = HPI['Country_Raw'].str.split(':').str[1].str.strip()

In [192]:
HPI

          Country_Raw     Quarter  Real_HPI       Country
144        AT:Austria  2000-03-31   98.2843       Austria
145        AT:Austria  2000-06-30   95.9464       Austria
146        AT:Austria  2000-09-30   93.7325       Austria
147        AT:Austria  2000-12-31   92.7328       Austria
148        AT:Austria  2001-03-31   96.5591       Austria
...               ...         ...       ...           ...
5750  ZA:South Africa  2024-12-31   87.9349  South Africa
5751  ZA:South Africa  2025-03-31   87.9561  South Africa
5752  ZA:South Africa  2025-06-30   88.0077  South Africa
5753  ZA:South Africa  2025-09-30   88.3881  South Africa
5754  ZA:South Africa  2025-12-31   89.4681  South Africa

[5436 rows x 4 columns]

In [193]:
first_entries = HPI.groupby('Country').first()
print(first_entries)

                        Country_Raw     Quarter  Real_HPI
Country
Australia              AU:Australia  2000-03-31   55.9766
Austria                  AT:Austria  2000-03-31   98.2843
Belgium                  BE:Belgium  2000-03-31   66.7303
Brazil                    BR:Brazil  2001-03-31   52.2932
Bulgaria                BG:Bulgaria  2000-03-31   59.6427
Canada                    CA:Canada  2000-03-31   60.0711
Chile                      CL:Chile  2002-03-31   73.3761
China                      CN:China  2005-06-30   87.9500
Colombia                CO:Colombia  2000-03-31   76.9397
Croatia                  HR:Croatia  2000-03-31   74.2766
Cyprus                    CY:Cyprus  2002-03-31   55.2744
Czechia                  CZ:Czechia  2008-03-31  105.4167
Denmark                  DK:Denmark  2000-03-31   72.6628
Estonia                  EE:Estonia  2005-03-31  101.9719
Finland                  FI:Finland  2000-03-31   73.7069
France                    FR:France  2000-03-31   57.0587
Germany                  DE:Germany  2000-03-31  118.7491
Greece                    GR:Greece  2000-03-31   77.6642
Hong Kong SAR      HK:Hong Kong SAR  2000-03-31   66.4739
Hungary                  HU:Hungary  2000-03-31   82.1241
Iceland                  IS:Iceland  2000-03-31   85.0683
India                      IN:India  2009-03-31   88.9013
Indonesia              ID:Indonesia  2002-03-31  139.3968
Ireland                  IE:Ireland  2000-03-31   94.4460
Israel                    IL:Israel  2000-03-31   92.3658
Italy                      IT:Italy  2000-03-31   76.3039
Japan                      JP:Japan  2000-03-31  141.4415
Korea                      KR:Korea  2000-03-31   82.5668
Latvia                    LV:Latvia  2006-03-31  149.2465
Lithuania              LT:Lithuania  2000-03-31   41.9676
Luxembourg            LU:Luxembourg  2007-03-31   97.3951
Malaysia                MY:Malaysia  2000-03-31   86.2324
Malta                      MT:Malta  2005-03-31   70.9393
Mexico                    MX:Mexico  2005-03-31   90.9971
Morocco                  MA:Morocco  2007-03-31  102.5356
Netherlands          NL:Netherlands  2000-03-31   84.0758
New Zealand          NZ:New Zealand  2000-03-31   62.5862
North Macedonia  MK:North Macedonia  2000-03-31   72.7104
Norway                    NO:Norway  2000-03-31   62.6810
Peru                        PE:Peru  2000-03-31   83.5080
Philippines          PH:Philippines  2008-03-31  107.8330
Poland                    PL:Poland  2010-03-31  100.0602
Portugal                PT:Portugal  2000-03-31  118.7076
Romania                  RO:Romania  2009-03-31  119.3204
Russia                    RU:Russia  2001-03-31   34.9443
Serbia                    RS:Serbia  2000-03-31  135.2788
Singapore              SG:Singapore  2000-03-31   87.8241
Slovakia                SK:Slovakia  2006-03-31   82.1598
Slovenia                SI:Slovenia  2007-03-31  110.1683
South Africa        ZA:South Africa  2000-03-31   56.8608
Spain                      ES:Spain  2000-03-31   59.2993
Sweden                    SE:Sweden  2000-03-31   53.3734
Switzerland          CH:Switzerland  2000-03-31   77.5257
Thailand                TH:Thailand  2000-03-31   96.8028
Türkiye                  TR:Türkiye  2010-03-31   98.6380
United Kingdom    GB:United Kingdom  2000-03-31   62.6002
United States      US:United States  2000-03-31   95.1841

The latest start is 2010-03-31 - Turkey, so I will start from then

In [194]:
print(HPI['Quarter'].dtype)

object

In [195]:
HPI = HPI[HPI['Quarter'] >= '2010-01-01'].copy()

In [196]:
HPI_clean = HPI[['Country', 'Quarter', 'Real_HPI']].reset_index(drop=True) # I don't want a new column with the og indexes

In [197]:
HPI_clean

           Country     Quarter  Real_HPI
0          Austria  2010-03-31  100.2528
1          Austria  2010-06-30   99.5266
2          Austria  2010-09-30   99.7640
3          Austria  2010-12-31  100.4564
4          Austria  2011-03-31  101.9770
...            ...         ...       ...
3612  South Africa  2024-12-31   87.9349
3613  South Africa  2025-03-31   87.9561
3614  South Africa  2025-06-30   88.0077
3615  South Africa  2025-09-30   88.3881
3616  South Africa  2025-12-31   89.4681

[3617 rows x 3 columns]

To ensure naming differences don't exclude important data, I will create naming banks and when merging will perform a consistency check across the datasets.

In [198]:
HPI_countries = set (HPI_clean['Country'].unique())
print(f"Total countries in HPI: {len(HPI_countries)}")

Total countries in HPI: 57

In [199]:
HPI_countries

{'Australia',
 'Austria',
 'Belgium',
 'Brazil',
 'Bulgaria',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong SAR',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Malta',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'North Macedonia',
 'Norway',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sweden',
 'Switzerland',
 'Thailand',
 'Türkiye',
 'United Kingdom',
 'United States'}

# Data 2: The central Banks policy rates

The central Banks policy rates -  set tracks the evolution of policy rates across the world. The policy rate is an important instrument used by central banks to implement their monetary policy. The data DOES NOT ACCOUNT for inflation, so we will need to get the data for inflation next :$Real\ Rate = Nominal\ Policy\ Rate - Inflation\ Rate$

In [200]:
CBPR_raw = pd.read_csv("raw_data/Central_bank_policy_rates.csv", skiprows=5)
CBPR = CBPR_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period','OBS_VALUE:Value']].copy()
CBPR.columns = ['Country_Raw', 'Monthly', 'Nominal Interest Rate']

In [201]:
CBPR

          Country_Raw     Monthly  Nominal Interest Rate
0        AR:Argentina  2010-01-31                   9.50
1        AR:Argentina  2010-02-28                   9.50
2        AR:Argentina  2010-03-31                   9.50
3        AR:Argentina  2010-04-30                   9.50
4        AR:Argentina  2010-05-31                   9.50
...               ...         ...                    ...
7113  ZA:South Africa  2025-08-31                   7.00
7114  ZA:South Africa  2025-09-30                   7.00
7115  ZA:South Africa  2025-10-31                   7.00
7116  ZA:South Africa  2025-11-30                   6.75
7117  ZA:South Africa  2025-12-31                   6.75

[7118 rows x 3 columns]

In [202]:
CBPR['Country'] = CBPR['Country_Raw'].str.split(':').str[1]
CBPR = CBPR[['Country', 'Monthly', 'Nominal Interest Rate']].copy()

In [203]:
CBPR

           Country     Monthly  Nominal Interest Rate
0        Argentina  2010-01-31                   9.50
1        Argentina  2010-02-28                   9.50
2        Argentina  2010-03-31                   9.50
3        Argentina  2010-04-30                   9.50
4        Argentina  2010-05-31                   9.50
...            ...         ...                    ...
7113  South Africa  2025-08-31                   7.00
7114  South Africa  2025-09-30                   7.00
7115  South Africa  2025-10-31                   7.00
7116  South Africa  2025-11-30                   6.75
7117  South Africa  2025-12-31                   6.75

[7118 rows x 3 columns]

Because the data is monthly for the interest rates, but quarterly for the house price index, I have to make a mean for every quarter

1. Check if the monthly data is an 'object' or 'datatime'

In [204]:
print(CBPR['Monthly'].dtype)

object

In [205]:
CBPR['Monthly'] = pd.to_datetime(CBPR['Monthly'])
print(CBPR['Monthly'].dtype)

datetime64[ns]

2. Now that is a datetime, I make the quarterly mean with the same quarters as the HPI table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

 - Add a new column that indicates which month is in which Quater

In [206]:
CBPR.loc[:, 'temp_quater'] = CBPR['Monthly'].dt.to_period('Q')

In [207]:
CBPR

           Country    Monthly  Nominal Interest Rate temp_quater
0        Argentina 2010-01-31                   9.50      2010Q1
1        Argentina 2010-02-28                   9.50      2010Q1
2        Argentina 2010-03-31                   9.50      2010Q1
3        Argentina 2010-04-30                   9.50      2010Q2
4        Argentina 2010-05-31                   9.50      2010Q2
...            ...        ...                    ...         ...
7113  South Africa 2025-08-31                   7.00      2025Q3
7114  South Africa 2025-09-30                   7.00      2025Q3
7115  South Africa 2025-10-31                   7.00      2025Q4
7116  South Africa 2025-11-30                   6.75      2025Q4
7117  South Africa 2025-12-31                   6.75      2025Q4

[7118 rows x 4 columns]

In [208]:
CBPR = CBPR.groupby(['Country', 'temp_quater'])['Nominal Interest Rate'].mean().reset_index()
CBPR = CBPR.copy()
CBPR.loc[:, 'Quarter'] = CBPR['temp_quater'].dt.to_timestamp('Q')

In [209]:
CBPR

            Country temp_quater  Nominal Interest Rate    Quarter
0         Argentina      2010Q1               9.500000 2010-03-31
1         Argentina      2010Q2               9.500000 2010-06-30
2         Argentina      2010Q3               9.500000 2010-09-30
3         Argentina      2010Q4               9.500000 2010-12-31
4         Argentina      2011Q1               9.500000 2011-03-31
...             ...         ...                    ...        ...
2369  United States      2024Q4               4.625000 2024-12-31
2370  United States      2025Q1               4.375000 2025-03-31
2371  United States      2025Q2               4.375000 2025-06-30
2372  United States      2025Q3               4.291667 2025-09-30
2373  United States      2025Q4               3.791667 2025-12-31

[2374 rows x 4 columns]

In [210]:
final_columns = ['Country', 'Quarter', 'Nominal Interest Rate'] 
CBPR_clean = CBPR[final_columns]

In [211]:
CBPR_clean

            Country    Quarter  Nominal Interest Rate
0         Argentina 2010-03-31               9.500000
1         Argentina 2010-06-30               9.500000
2         Argentina 2010-09-30               9.500000
3         Argentina 2010-12-31               9.500000
4         Argentina 2011-03-31               9.500000
...             ...        ...                    ...
2369  United States 2024-12-31               4.625000
2370  United States 2025-03-31               4.375000
2371  United States 2025-06-30               4.375000
2372  United States 2025-09-30               4.291667
2373  United States 2025-12-31               3.791667

[2374 rows x 3 columns]

The country name bank for Interest Rates:

In [212]:
CBPR_countries = set (CBPR_clean['Country'].unique())
print(f"Total countries in Central Bank Policy Rates: {len(CBPR_countries)}")

Total countries in Central Bank Policy Rates: 40

# Data 3: Consumer prices

The consumer price index data set contains long series that track the overall change in the prices of goods and services purchased by households. Consumer price indices are a key macroeconomic indicator, for instance to measure inflation and assess purchasing power over time.

In [213]:
CPI_raw = pd.read_csv("raw_data/Consumer_prices_Yearly_change.csv", skiprows=5)#CPI_raw = Consumer prices index raw
CPI = CPI_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period','OBS_VALUE:Value']].copy()
CPI.columns = ['Country_Raw', 'Monthly', 'Change of inflation rate']

In [214]:
CPI

                   Country_Raw     Monthly  Change of inflation rate
0      AE:United Arab Emirates  2010-01-31                 -0.431897
1      AE:United Arab Emirates  2010-02-28                 -0.264243
2      AE:United Arab Emirates  2010-03-31                  0.682230
3      AE:United Arab Emirates  2010-04-30                  0.789923
4      AE:United Arab Emirates  2010-05-31                  0.876724
...                        ...         ...                       ...
12086          ZA:South Africa  2025-08-31                  3.303274
12087          ZA:South Africa  2025-09-30                  3.399981
12088          ZA:South Africa  2025-10-31                  3.603607
12089          ZA:South Africa  2025-11-30                  3.503496
12090          ZA:South Africa  2025-12-31                  3.600003

[12091 rows x 3 columns]

In [215]:
CPI['Country'] = CPI['Country_Raw'].str.split(':').str[1]
CPI = CPI[['Country', 'Monthly', 'Change of inflation rate']].copy()

The data for the consumer prices is monthly, but I need it in quarters

In [216]:
print(CPI['Monthly'].dtype)

object

2. It's an object so we change it to datetime

In [217]:
CPI['Monthly'] = pd.to_datetime(CPI['Monthly'])
print(CPI['Monthly'].dtype)

datetime64[ns]

4. Now that is a datetime, I make the quarterly mean with the same quarters as the HPI & CBPR table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

I insert a new column that indicates if the month belongs to Q1, Q2, Q3 or Q4

In [218]:
CPI.loc[:, 'temp_quater'] = CPI['Monthly'].dt.to_period('Q')

In [219]:
CPI = CPI.groupby(['Country', 'temp_quater'])['Change of inflation rate'].mean().reset_index()

In [220]:
CPI

            Country temp_quater  Change of inflation rate
0           Algeria      2010Q1                  4.323700
1           Algeria      2010Q2                  4.946776
2           Algeria      2010Q3                  3.465990
3           Algeria      2010Q4                  2.989893
4           Algeria      2011Q1                  3.495927
...             ...         ...                       ...
4027  United States      2024Q4                  2.745114
4028  United States      2025Q1                  2.737586
4029  United States      2025Q2                  2.445133
4030  United States      2025Q3                  2.877918
4031  United States      2025Q4                  2.706082

[4032 rows x 3 columns]

Now, let's make the temp_quarter column to look like the others (YYYY-03-31)

In [221]:
CPI.loc[:, 'Quarter'] = CPI['temp_quater'].dt.to_timestamp('Q')
final_columns = ['Country', 'Quarter', 'Change of inflation rate'] 
CPI_clean = CPI[final_columns].copy()

In [222]:
CPI_clean

            Country    Quarter  Change of inflation rate
0           Algeria 2010-03-31                  4.323700
1           Algeria 2010-06-30                  4.946776
2           Algeria 2010-09-30                  3.465990
3           Algeria 2010-12-31                  2.989893
4           Algeria 2011-03-31                  3.495927
...             ...        ...                       ...
4027  United States 2024-12-31                  2.745114
4028  United States 2025-03-31                  2.737586
4029  United States 2025-06-30                  2.445133
4030  United States 2025-09-30                  2.877918
4031  United States 2025-12-31                  2.706082

[4032 rows x 3 columns]

The country name bank for Inflation Rate:

In [223]:
CPI_countries = set (CPI_clean['Country'].unique())
print(f"Total countries in Consumer Prices: {len(CBPR_countries)}")

Total countries in Consumer Prices: 40

# DATA 4 : Quarterly real GDP growth

Adding Quarterly real GDP growth, as when the economy is booming, resulting in High GDP, people feel rich and buy houses, which drives prices up. In a response to the heating economy, Central banks often raise interest rates.  
The data is Year-over-Year Change ( comparing Q1 of 2010 to Q1 of 2011 )

In [224]:
GDP_growth_raw = pd.read_csv("raw_data/Quarterly_Real_Gdp_growth.csv")

In [225]:
GDP_growth_raw

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency of observation,ADJUSTMENT,Adjustment,REF_AREA,Reference area,...,CONF_STATUS,Confidentiality status,DECIMALS,Decimals,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,CURRENCY,Currency
0,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,RUS,Russia,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
1,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,SAU,Saudi Arabia,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
2,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,SAU,Saudi Arabia,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
3,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,RUS,Russia,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
4,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,RUS,Russia,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2918,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,CRI,Costa Rica,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
2919,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,CRI,Costa Rica,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
2920,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,CRI,Costa Rica,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
2921,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,CRI,Costa Rica,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable
2922,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN1@DF_QNA_EXPENDITURE_GR...,Quarterly real GDP growth - OECD countries,I,Q,Quarterly,Y,Calendar and seasonally adjusted,CRI,Costa Rica,...,F,Free (free for publication),1,One,A,Normal value,0,Units,_Z,Not applicable

In [226]:
GDP_growth = GDP_growth_raw[['Reference area', 'TIME_PERIOD','OBS_VALUE']].copy()
GDP_growth.columns = ['Country', 'Quarter', 'GDP growth']

In [227]:
GDP_growth

           Country  Quarter  GDP growth
0           Russia  2011-Q1    3.941124
1     Saudi Arabia  2011-Q1   11.811325
2     Saudi Arabia  2011-Q2   13.000325
3           Russia  2011-Q2    3.938645
4           Russia  2011-Q3    4.587799
...            ...      ...         ...
2918    Costa Rica  2024-Q4    4.137186
2919    Costa Rica  2025-Q1    3.786889
2920    Costa Rica  2025-Q2    4.879610
2921    Costa Rica  2025-Q3    5.130057
2922    Costa Rica  2025-Q4    4.555090

[2923 rows x 3 columns]

I see that the data is out of order, so:

In [228]:
GDP_growth = GDP_growth.sort_values(by =['Country', 'Quarter'])

In [229]:
GDP_growth

            Country  Quarter  GDP growth
1743      Argentina  2010-Q1    6.707061
1744      Argentina  2010-Q2   14.162760
1745      Argentina  2010-Q3   10.295741
1746      Argentina  2010-Q4    9.453359
1747      Argentina  2011-Q1    8.702046
...             ...      ...         ...
2690  United States  2024-Q4    2.399788
2691  United States  2025-Q1    2.019273
2692  United States  2025-Q2    2.080467
2693  United States  2025-Q3    2.335168
2694  United States  2025-Q4    1.989300

[2923 rows x 3 columns]

The quarterly data is not  in the format of the other

In [230]:
print(GDP_growth['Quarter'].dtype)

object

Now, to make them into the right format  
*Note*: Tried to do it like the previous: Q -> date, but it made the quarter in the beginning, not the end like the other data, so:

In [231]:
GDP_growth['Quarter'] = pd.PeriodIndex(GDP_growth['Quarter'], freq='Q') # to go into period objects
GDP_growth['Quarter'] = GDP_growth['Quarter'].dt.to_timestamp(how='end').dt.normalize() # convert to the end of a quarter

In [232]:
GDP_growth_clean = GDP_growth.sort_values(by =['Country', 'Quarter'])

In [233]:
GDP_growth_clean

            Country    Quarter  GDP growth
1743      Argentina 2010-03-31    6.707061
1744      Argentina 2010-06-30   14.162760
1745      Argentina 2010-09-30   10.295741
1746      Argentina 2010-12-31    9.453359
1747      Argentina 2011-03-31    8.702046
...             ...        ...         ...
2690  United States 2024-12-31    2.399788
2691  United States 2025-03-31    2.019273
2692  United States 2025-06-30    2.080467
2693  United States 2025-09-30    2.335168
2694  United States 2025-12-31    1.989300

[2923 rows x 3 columns]

The country name bank for GDP growth:

In [234]:
GDP_growth_countries = set (GDP_growth_clean['Country'].unique())
print(f"Total countries in GDP growth: {len(GDP_growth_countries)}")

Total countries in GDP growth: 46

# Data 5: Unemployment data

Unemployment is another factor that can help us get a glimpse into the "demand side" of the economy. If unemployment is high, demand for residential properties will drop as people can't get mortgages, even if interest rates are low.

In [235]:
Unemployment_raw = pd.read_csv('raw_data/Quarterly_unemployement_rates.csv')

In [236]:
Unemployment_raw= Unemployment_raw[['Reference area', 'TIME_PERIOD','OBS_VALUE']].copy()
Unemployment_raw.columns = ['Country', 'Quarter', 'Unemployment rate']

In [237]:
Unemployment_raw

        Country  Quarter  Unemployment rate
0         Japan  2010-Q1           5.033333
1         Japan  2010-Q2           5.133333
2         Japan  2010-Q3           5.066667
3         Japan  2010-Q4           5.000000
4         Japan  2011-Q1           4.733333
...         ...      ...                ...
2616  Australia  2025-Q3           4.319749
2617  Australia  2025-Q4           4.253215
2618     Israel  2011-Q4           5.400000
2619     Israel  2024-Q4           2.715707
2620    Türkiye  2013-Q4           9.133333

[2621 rows x 3 columns]

I see that the data is not in order for all the countries, so:

In [238]:
Unemployment_raw = Unemployment_raw.sort_values(by =['Country', 'Quarter'])

In [239]:
Unemployment_raw

            Country  Quarter  Unemployment rate
2554      Australia  2010-Q1           5.329225
2555      Australia  2010-Q2           5.290923
2556      Australia  2010-Q3           5.124990
2557      Australia  2010-Q4           5.090152
2558      Australia  2011-Q1           4.967735
...             ...      ...                ...
122   United States  2024-Q3           4.166667
123   United States  2024-Q4           4.133333
124   United States  2025-Q1           4.133333
125   United States  2025-Q2           4.200000
126   United States  2025-Q3           4.333333

[2621 rows x 3 columns]

Resetting the index

In [240]:
Unemployment_raw = Unemployment_raw.reset_index(drop=True)

In [241]:
Unemployment_raw

            Country  Quarter  Unemployment rate
0         Australia  2010-Q1           5.329225
1         Australia  2010-Q2           5.290923
2         Australia  2010-Q3           5.124990
3         Australia  2010-Q4           5.090152
4         Australia  2011-Q1           4.967735
...             ...      ...                ...
2616  United States  2024-Q3           4.166667
2617  United States  2024-Q4           4.133333
2618  United States  2025-Q1           4.133333
2619  United States  2025-Q2           4.200000
2620  United States  2025-Q3           4.333333

[2621 rows x 3 columns]

The format of the Quarter doesn't match the previous tables, so:

In [242]:
print(Unemployment_raw['Quarter'].dtype)

object

In [243]:
Unemployment_raw['Quarter'] = pd.PeriodIndex(Unemployment_raw['Quarter'], freq='Q') # to go into period objects
Unemployment_raw['Quarter'] = Unemployment_raw['Quarter'].dt.to_timestamp(how='end').dt.normalize() # convert to the end of a quarter

In [244]:
Unemployment_clean = Unemployment_raw. copy()

In [245]:
Unemployment_clean

            Country    Quarter  Unemployment rate
0         Australia 2010-03-31           5.329225
1         Australia 2010-06-30           5.290923
2         Australia 2010-09-30           5.124990
3         Australia 2010-12-31           5.090152
4         Australia 2011-03-31           4.967735
...             ...        ...                ...
2616  United States 2024-09-30           4.166667
2617  United States 2024-12-31           4.133333
2618  United States 2025-03-31           4.133333
2619  United States 2025-06-30           4.200000
2620  United States 2025-09-30           4.333333

[2621 rows x 3 columns]

The country name bank for Unemployment rate:

In [246]:
Unemployment_countries = set (Unemployment_clean['Country'].unique())
print(f"Total countries in Unemployment: {len(Unemployment_countries)}")

Total countries in Unemployment: 41

# Common countries

In [247]:
common_countries = set.intersection(HPI_countries,CBPR_countries, CPI_countries, GDP_growth_countries, Unemployment_countries )

In [248]:
common_countries

{'Australia',
 'Canada',
 'Chile',
 'Colombia',
 'Czechia',
 'Denmark',
 'Hungary',
 'Iceland',
 'Israel',
 'Japan',
 'Korea',
 'Mexico',
 'New Zealand',
 'Norway',
 'Poland',
 'Sweden',
 'Switzerland',
 'Türkiye',
 'United Kingdom',
 'United States'}

I am worried of missing data because of naming, so:

In [249]:
dropped_countries = HPI_countries - common_countries # Using HPI as it's the dependent variable and the data with most countries

In [250]:
dropped_countries

{'Austria',
 'Belgium',
 'Brazil',
 'Bulgaria',
 'China',
 'Croatia',
 'Cyprus',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong SAR',
 'India',
 'Indonesia',
 'Ireland',
 'Italy',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Malta',
 'Morocco',
 'Netherlands',
 'North Macedonia',
 'Peru',
 'Philippines',
 'Portugal',
 'Romania',
 'Russia',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Thailand'}

I want to see which country does not exist in the other datasets

In [251]:
for country in sorted(list(dropped_countries)):
    missing_from = []
    if country not in GDP_growth_countries: missing_from.append("GDP")
    if country not in Unemployment_countries: missing_from.append("Unemployment")
    if country not in CBPR_countries: missing_from.append("Rates")
    if country not in CPI_countries: missing_from.append("CPI")
    
    print(f" {country.ljust(20)} | Missing from: {', '.join(missing_from)}")

 Austria              | Missing from: Rates
 Belgium              | Missing from: Rates
 Brazil               | Missing from: Unemployment
 Bulgaria             | Missing from: GDP, Rates
 China                | Missing from: GDP, Unemployment
 Croatia              | Missing from: GDP
 Cyprus               | Missing from: GDP, Unemployment, Rates
 Estonia              | Missing from: Rates
 Finland              | Missing from: Rates
 France               | Missing from: Rates
 Germany              | Missing from: Rates
 Greece               | Missing from: Rates
 Hong Kong SAR        | Missing from: GDP, Unemployment
 India                | Missing from: Unemployment
 Indonesia            | Missing from: Unemployment
 Ireland              | Missing from: Rates
 Italy                | Missing from: Rates
 Latvia               | Missing from: Rates
 Lithuania            | Missing from: Rates
 Luxembourg           | Missing from: Rates
 Malaysia             | Missing from: GDP, Unemployment
 Malta                | Missing from: GDP, Unemployment, Rates
 Morocco              | Missing from: GDP, Unemployment
 Netherlands          | Missing from: Rates
 North Macedonia      | Missing from: GDP, Unemployment
 Peru                 | Missing from: GDP, Unemployment
 Philippines          | Missing from: GDP, Unemployment
 Portugal             | Missing from: Rates
 Romania              | Missing from: GDP
 Russia               | Missing from: Unemployment
 Serbia               | Missing from: GDP, Unemployment
 Singapore            | Missing from: GDP, Unemployment, Rates
 Slovakia             | Missing from: GDP, Unemployment, Rates
 Slovenia             | Missing from: Rates
 South Africa         | Missing from: Unemployment
 Spain                | Missing from: Rates
 Thailand             | Missing from: GDP, Unemployment

A lot of countries are missing only from **'Rates'**  
I realize it's because they are part of the **Euro area** - looking into the Central Bank Rates file, they are grouped in the 'Euro Area'. To correct that - if the country is in the Eurozone, then we will use the Euro Area interest rate:

In [252]:
eurozone = [
    'Austria', 'Belgium', 'Finland', 'France', 'Germany', 'Greece', 
    'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 
    'Netherlands', 'Portugal', 'Slovakia', 'Slovenia', 'Spain', 'Estonia'
]

euro_rates = CBPR_clean[CBPR_clean['Country'] == 'Euro area']

In [253]:
euro_area = []
for country in eurozone:
    temp_df = euro_rates.copy()
    temp_df['Country'] = country
    euro_area.append(temp_df)

Adding them to the dataset:

In [254]:
CBPR_clean = pd.concat([CBPR_clean] + euro_area, ignore_index=True)

In [255]:
rates_countries = set(CBPR_clean['Country'].unique())

Finally, let's see which countries we have:

In [256]:
common_countries_euro_zone = set.intersection(HPI_countries,rates_countries, CPI_countries, GDP_growth_countries, Unemployment_countries )

In [257]:
common_countries_euro_zone

{'Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Chile',
 'Colombia',
 'Czechia',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Iceland',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Poland',
 'Portugal',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'Türkiye',
 'United Kingdom',
 'United States'}

In [258]:
print(f"New Common Country Count: {len(common_countries_euro_zone)}")

New Common Country Count: 36

# Merge into a master table

To merge, I need all the quarter data be datetime

In [259]:
HPI_clean['Quarter'] = pd.to_datetime(HPI_clean['Quarter'])
CPI_clean['Quarter'] = pd.to_datetime(CPI_clean['Quarter'])
CBPR_clean['Quarter'] = pd.to_datetime(CBPR_clean['Quarter'])
GDP_growth_clean['Quarter'] = pd.to_datetime(GDP_growth_clean['Quarter'])
Unemployment_clean['Quarter'] = pd.to_datetime(Unemployment_clean['Quarter'])

In [260]:
master = pd.merge(HPI_clean, GDP_growth_clean, on=['Country', 'Quarter'], how='inner')

# Add Unemployment
master = pd.merge(master, Unemployment_clean, on=['Country', 'Quarter'], how='inner')

# Add Central Bank Policy Rates (CBPR)
master = pd.merge(master, CBPR_clean, on=['Country', 'Quarter'], how='inner')

# Add CPI
master = pd.merge(master, CPI_clean, on=['Country', 'Quarter'], how='inner')

# Sort to keep everything organized
master = master.sort_values(by=['Country', 'Quarter']).reset_index(drop=True)

In [261]:
master

,Country,Quarter,Real_HPI,GDP growth,Unemployment rate,Nominal Interest Rate,Change of inflation rate
0,Australia,2010-03-31,99.9682,2.237068,5.329225,3.833333,2.918919
1,Australia,2010-06-30,101.2842,2.242561,5.290923,4.416667,3.121636
2,Australia,2010-09-30,99.2963,2.598016,5.124990,4.500000,2.878465
3,Australia,2010-12-31,99.4624,2.631979,5.090152,4.666667,2.757158
4,Australia,2011-03-31,97.1941,1.879672,4.967735,4.750000,3.256303
...,...,...,...,...,...,...,...
2120,United States,2024-09-30,160.2521,2.791390,4.166667,5.208333,2.622039
2121,United States,2024-12-31,161.3926,2.399788,4.133333,4.625000,2.745114
2122,United States,2025-03-31,159.9432,2.019273,4.133333,4.375000,2.737586
2123,United States,2025-06-30,158.3531,2.080467,4.200000,4.375000,2.445133
2124,United States,2025-09-30,157.6734,2.335168,4.333333,4.291667,2.877918

# Finding the 'real' interest rates & HPI growth

###  HPI growth for Year-to-year change

Right now, we have data about the 'level' of the Real Price Index, but we need to know how much it grows quarter to quarter to compare it to the real interest and inflation rate

We group countries so the calculations don't leak from the last entry of one country to another

In [262]:
master['HPI_Growth'] = master.groupby('Country')['Real_HPI'].pct_change(periods=4) * 100

### Calculating the Real Interest Rate (Fisher Eq.)

The data we currently have for interest rates does not account for inflation, but we just got the quarterly inflation change
We will get the real interest rate by : $Real\ Rate = Nominal\ Policy\ Rate - Inflation\ Rate$


(Nominal - does not account for inflation; Real - accounts for inflation)

In [265]:
master['Real_Rate'] = master['Nominal Interest Rate'] - master['Change of inflation rate']

In [266]:
master = master.dropna().reset_index(drop=True)

In [267]:
master

,Country,Quarter,Real_HPI,GDP growth,Unemployment rate,Nominal Interest Rate,Change of inflation rate,HPI_Growth,Real_Rate
0,Australia,2011-03-31,97.1941,1.879672,4.967735,4.750000,3.256303,-2.774982,1.493697
1,Australia,2011-06-30,95.6559,2.472139,4.963181,4.750000,3.549061,-5.556938,1.200939
2,Australia,2011-09-30,93.4029,3.175238,5.195016,4.750000,3.419689,-5.935166,1.330311
3,Australia,2011-12-31,92.6571,3.455913,5.205014,4.500000,2.992776,-6.842083,1.507224
4,Australia,2012-03-31,93.1231,4.839548,5.141726,4.250000,1.627670,-4.188526,2.622330
...,...,...,...,...,...,...,...,...,...
1976,United States,2024-09-30,160.2521,2.791390,4.166667,5.208333,2.622039,1.066657,2.586295
1977,United States,2024-12-31,161.3926,2.399788,4.133333,4.625000,2.745114,0.699312,1.879886
1978,United States,2025-03-31,159.9432,2.019273,4.133333,4.375000,2.737586,-0.122206,1.637414
1979,United States,2025-06-30,158.3531,2.080467,4.200000,4.375000,2.445133,-0.645120,1.929867
1980,United States,2025-09-30,157.6734,2.335168,4.333333,4.291667,2.877918,-1.609152,1.413749

In [270]:
print(master[['HPI_Growth', 'Real_Rate', 'GDP growth', 'Unemployment rate']].describe())

        HPI_Growth    Real_Rate   GDP growth  Unemployment rate
count  1981.000000  1981.000000  1981.000000        1981.000000
mean      2.612484    -1.101290     2.105414           7.096061
std       6.755500     4.236418     3.968845           4.068486
min     -21.731019   -68.550348   -21.671078           1.866667
25%      -0.644985    -1.898460     0.637906           4.333333
50%       2.714461    -0.618542     2.040382           6.200000
75%       6.227296     0.591751     3.416112           8.466666
max      57.237322     9.895876    28.160239          28.066670