In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

# Data preparation & Cleaning
 This file aims to prepare data for analysis

## Data used:

 When adding new data, I will be adding it here. If explanation is need about the data, it will be provided here.

### 1. Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org/RPP](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))

The selected residential property prices data set shows the most representative property price indicator for each country. For most economies, this series refers to the whole country and covers the entire market: all property types, both new and existing vintages.

### 2. The central Banks policy rates - 2010-2025, monthly ([Bis.data.org/CBPR](https://data.bis.org/topics/CBPOL/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DM%255EYEAR%3D2010%257C2011%257C2012%257C2013%257C2014%257C2018%257C2016%257C2017%257C2015%257C2019%257C2020%257C2021%257C2022%257C2025%257C2024%257C2023))

The BIS central bank policy rates data set tracks the evolution of policy rates across the world. The policy rate is an important instrument used by central banks to implement their monetary policy.

### 3. Consumer prices - 2010-2025, Changes over one year, ([Bis.data.org/CPI](https://data.bis.org/topics/CPI/data?data_view=table&rows=REF_AREA&cols=FREQ%7CTIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DA%257CM%255EUNIT_MEASURE%3D771%255EYEAR%3D2010%257C2011%257C2012%257C2013%257C2014%257C2018%257C2017%257C2016%257C2015%257C2019%257C2020%257C2021%257C2022%257C2023%257C2024%257C2025))

The consumer price index data set contains long series that track the overall change in the prices of goods and services purchased by households. Consumer price indices are a key macroeconomic indicator, for instance to measure inflation and assess purchasing power over time.

### 4. Real GDP Growth - 2010-2025, YoY ([OECD](https://data-explorer.oecd.org/vis?df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_NAMAIN1%40DF_QNA_EXPENDITURE_GROWTH_OECD&df[ag]=OECD.SDD.NAD&df[vs]=1.1&dq=Q..AUS%2BAUT%2BBEL%2BCAN%2BCHL%2BCOL%2BCRI%2BCZE%2BDNK%2BEST%2BFIN%2BFRA%2BDEU%2BGRC%2BHUN%2BISL%2BIRL%2BISR%2BITA%2BJPN%2BKOR%2BLVA%2BLTU%2BLUX%2BMEX%2BNLD%2BNZL%2BNOR%2BPOL%2BPRT%2BSVK%2BSVN%2BESP%2BSWE%2BCHE%2BTUR%2BGBR%2BUSA%2BARG%2BBRA%2BCHN%2BIND%2BIDN%2BRUS%2BSAU%2BZAF...B1GQ......G1.&ly[cl]=TIME_PERIOD&ly[rw]=REF_AREA&to[TIME_PERIOD]=false&vw=tb&lc=en&pg=0&pd=2010-Q1%2C2025-Q4))

This table presents Gross Domestic Product (GDP) and its main components according to the expenditure approach. Data is presented as growth rates.

## 5. Monthly Unemployment Rates - 2010-2025, ([OECD](https://data-explorer.oecd.org/vis?lc=en&tm=unemployement&pg=0&snb=87&vw=tb&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_LFS%40DF_IALFS_UNE_M&df[ag]=OECD.SDD.TPS&df[vs]=1.0&dq=AUS%2BAUT%2BBEL%2BCAN%2BCHL%2BCOL%2BCRI%2BCZE%2BDNK%2BEST%2BFIN%2BFRA%2BDEU%2BGRC%2BHUN%2BISL%2BIRL%2BISR%2BITA%2BJPN%2BKOR%2BLVA%2BLTU%2BLUX%2BMEX%2BNLD%2BNZL%2BNOR%2BPOL%2BPRT%2BSVK%2BSVN%2BESP%2BSWE%2BCHE%2BTUR%2BGBR%2BUSA%2BBGR%2BHRV%2BROU..._Z.Y._T.Y_GE15..Q&pd=2010-Q1%2C2025-Q4&to[TIME_PERIOD]=false))

The infra-annual data flow on the monthly unemployment rate is a subset of the infra-annual labor statistics database, which contains quarterly statistics

# Data 1: Residential property prices - index , real(adjusted for inflation)

In [28]:
HPI_raw = pd.read_csv("raw_data/Housing_price_index_real.csv.csv", skiprows=7)
HPI = HPI_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']].copy()
HPI.columns = ['Country_Raw', 'Quarter', 'Real_HPI']

In [29]:
HPI

                                   Country_Raw     Quarter  Real_HPI
0     4T:Emerging market economies (aggregate)  2007-12-31   95.7745
1     4T:Emerging market economies (aggregate)  2008-03-31   95.0590
2     4T:Emerging market economies (aggregate)  2008-06-30   95.3475
3     4T:Emerging market economies (aggregate)  2008-09-30   95.6345
4     4T:Emerging market economies (aggregate)  2008-12-31   95.3757
...                                        ...         ...       ...
5750                           ZA:South Africa  2024-12-31   87.9349
5751                           ZA:South Africa  2025-03-31   87.9561
5752                           ZA:South Africa  2025-06-30   88.0077
5753                           ZA:South Africa  2025-09-30   88.3881
5754                           ZA:South Africa  2025-12-31   89.4681

[5755 rows x 3 columns]

I see there are aggregate data I do not need, so I will use a mask

In [33]:
mask = HPI['Country_Raw'].str.contains('aggregate|economies|World|area', case=False)
HPI = HPI[~mask].copy()

In [34]:
HPI

          Country_Raw     Quarter  Real_HPI       Country
144        AT:Austria  2000-03-31   98.2843       Austria
145        AT:Austria  2000-06-30   95.9464       Austria
146        AT:Austria  2000-09-30   93.7325       Austria
147        AT:Austria  2000-12-31   92.7328       Austria
148        AT:Austria  2001-03-31   96.5591       Austria
...               ...         ...       ...           ...
5750  ZA:South Africa  2024-12-31   87.9349  South Africa
5751  ZA:South Africa  2025-03-31   87.9561  South Africa
5752  ZA:South Africa  2025-06-30   88.0077  South Africa
5753  ZA:South Africa  2025-09-30   88.3881  South Africa
5754  ZA:South Africa  2025-12-31   89.4681  South Africa

[5436 rows x 4 columns]

Now, to remove the country code codes

In [39]:
HPI['Country'] = HPI['Country_Raw'].str.split(':').str[1].str.strip()

In [40]:
HPI

          Country_Raw     Quarter  Real_HPI       Country
144        AT:Austria  2000-03-31   98.2843       Austria
145        AT:Austria  2000-06-30   95.9464       Austria
146        AT:Austria  2000-09-30   93.7325       Austria
147        AT:Austria  2000-12-31   92.7328       Austria
148        AT:Austria  2001-03-31   96.5591       Austria
...               ...         ...       ...           ...
5750  ZA:South Africa  2024-12-31   87.9349  South Africa
5751  ZA:South Africa  2025-03-31   87.9561  South Africa
5752  ZA:South Africa  2025-06-30   88.0077  South Africa
5753  ZA:South Africa  2025-09-30   88.3881  South Africa
5754  ZA:South Africa  2025-12-31   89.4681  South Africa

[5436 rows x 4 columns]

In [42]:
first_entries = HPI.groupby('Country').first()
print(first_entries)

                        Country_Raw     Quarter  Real_HPI
Country
Australia              AU:Australia  2000-03-31   55.9766
Austria                  AT:Austria  2000-03-31   98.2843
Belgium                  BE:Belgium  2000-03-31   66.7303
Brazil                    BR:Brazil  2001-03-31   52.2932
Bulgaria                BG:Bulgaria  2000-03-31   59.6427
Canada                    CA:Canada  2000-03-31   60.0711
Chile                      CL:Chile  2002-03-31   73.3761
China                      CN:China  2005-06-30   87.9500
Colombia                CO:Colombia  2000-03-31   76.9397
Croatia                  HR:Croatia  2000-03-31   74.2766
Cyprus                    CY:Cyprus  2002-03-31   55.2744
Czechia                  CZ:Czechia  2008-03-31  105.4167
Denmark                  DK:Denmark  2000-03-31   72.6628
Estonia                  EE:Estonia  2005-03-31  101.9719
Finland                  FI:Finland  2000-03-31   73.7069
France                    FR:France  2000-03-31   57.0587
Germany                  DE:Germany  2000-03-31  118.7491
Greece                    GR:Greece  2000-03-31   77.6642
Hong Kong SAR      HK:Hong Kong SAR  2000-03-31   66.4739
Hungary                  HU:Hungary  2000-03-31   82.1241
Iceland                  IS:Iceland  2000-03-31   85.0683
India                      IN:India  2009-03-31   88.9013
Indonesia              ID:Indonesia  2002-03-31  139.3968
Ireland                  IE:Ireland  2000-03-31   94.4460
Israel                    IL:Israel  2000-03-31   92.3658
Italy                      IT:Italy  2000-03-31   76.3039
Japan                      JP:Japan  2000-03-31  141.4415
Korea                      KR:Korea  2000-03-31   82.5668
Latvia                    LV:Latvia  2006-03-31  149.2465
Lithuania              LT:Lithuania  2000-03-31   41.9676
Luxembourg            LU:Luxembourg  2007-03-31   97.3951
Malaysia                MY:Malaysia  2000-03-31   86.2324
Malta                      MT:Malta  2005-03-31   70.9393
Mexico                    MX:Mexico  2005-03-31   90.9971
Morocco                  MA:Morocco  2007-03-31  102.5356
Netherlands          NL:Netherlands  2000-03-31   84.0758
New Zealand          NZ:New Zealand  2000-03-31   62.5862
North Macedonia  MK:North Macedonia  2000-03-31   72.7104
Norway                    NO:Norway  2000-03-31   62.6810
Peru                        PE:Peru  2000-03-31   83.5080
Philippines          PH:Philippines  2008-03-31  107.8330
Poland                    PL:Poland  2010-03-31  100.0602
Portugal                PT:Portugal  2000-03-31  118.7076
Romania                  RO:Romania  2009-03-31  119.3204
Russia                    RU:Russia  2001-03-31   34.9443
Serbia                    RS:Serbia  2000-03-31  135.2788
Singapore              SG:Singapore  2000-03-31   87.8241
Slovakia                SK:Slovakia  2006-03-31   82.1598
Slovenia                SI:Slovenia  2007-03-31  110.1683
South Africa        ZA:South Africa  2000-03-31   56.8608
Spain                      ES:Spain  2000-03-31   59.2993
Sweden                    SE:Sweden  2000-03-31   53.3734
Switzerland          CH:Switzerland  2000-03-31   77.5257
Thailand                TH:Thailand  2000-03-31   96.8028
Türkiye                  TR:Türkiye  2010-03-31   98.6380
United Kingdom    GB:United Kingdom  2000-03-31   62.6002
United States      US:United States  2000-03-31   95.1841

The latest start is 2010-03-31 - Turkey, so I will start from then

In [43]:
print(HPI['Quarter'].dtype)

object

In [48]:
HPI = HPI[HPI['Quarter'] >= '2010-01-01'].copy()

In [56]:
HPI_clean = HPI[['Country', 'Quarter', 'Real_HPI']].reset_index(drop=True) # I don't want a new column with the og indexes

In [57]:
HPI_clean

           Country     Quarter  Real_HPI
0          Austria  2010-03-31  100.2528
1          Austria  2010-06-30   99.5266
2          Austria  2010-09-30   99.7640
3          Austria  2010-12-31  100.4564
4          Austria  2011-03-31  101.9770
...            ...         ...       ...
3612  South Africa  2024-12-31   87.9349
3613  South Africa  2025-03-31   87.9561
3614  South Africa  2025-06-30   88.0077
3615  South Africa  2025-09-30   88.3881
3616  South Africa  2025-12-31   89.4681

[3617 rows x 3 columns]

To ensure naming differences don't exclude important data, I will create naming banks and when merging will perform a consistency check across the datasets.

In [58]:
HPI_countries = set (HPI_clean['Country'].unique())
print(f"Total countries in HPI: {len(HPI_countries)}")

Total countries in HPI: 57

In [59]:
HPI_countries

{'Australia',
 'Austria',
 'Belgium',
 'Brazil',
 'Bulgaria',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong SAR',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Malta',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'North Macedonia',
 'Norway',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sweden',
 'Switzerland',
 'Thailand',
 'Türkiye',
 'United Kingdom',
 'United States'}

# Data 2: The central Banks policy rates

The central Banks policy rates -  set tracks the evolution of policy rates across the world. The policy rate is an important instrument used by central banks to implement their monetary policy. The data DOES NOT ACCOUNT for inflation, so we will need to get the data for inflation next :$Real\ Rate = Nominal\ Policy\ Rate - Inflation\ Rate$

In [75]:
CBPR_raw = pd.read_csv("raw_data/Central_bank_policy_rates.csv", skiprows=5)
CBPR = CBPR_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period','OBS_VALUE:Value']].copy()
CBPR.columns = ['Country_Raw', 'Monthly', 'Interest Rate']

In [76]:
CBPR

          Country_Raw     Monthly  Interest Rate
0        AR:Argentina  2010-01-31           9.50
1        AR:Argentina  2010-02-28           9.50
2        AR:Argentina  2010-03-31           9.50
3        AR:Argentina  2010-04-30           9.50
4        AR:Argentina  2010-05-31           9.50
...               ...         ...            ...
7113  ZA:South Africa  2025-08-31           7.00
7114  ZA:South Africa  2025-09-30           7.00
7115  ZA:South Africa  2025-10-31           7.00
7116  ZA:South Africa  2025-11-30           6.75
7117  ZA:South Africa  2025-12-31           6.75

[7118 rows x 3 columns]

In [77]:
CBPR['Country'] = CBPR['Country_Raw'].str.split(':').str[1]
CBPR = CBPR[['Country', 'Monthly', 'Interest Rate']].copy()

In [78]:
CBPR

           Country     Monthly  Interest Rate
0        Argentina  2010-01-31           9.50
1        Argentina  2010-02-28           9.50
2        Argentina  2010-03-31           9.50
3        Argentina  2010-04-30           9.50
4        Argentina  2010-05-31           9.50
...            ...         ...            ...
7113  South Africa  2025-08-31           7.00
7114  South Africa  2025-09-30           7.00
7115  South Africa  2025-10-31           7.00
7116  South Africa  2025-11-30           6.75
7117  South Africa  2025-12-31           6.75

[7118 rows x 3 columns]

Because the data is monthly for the interest rates, but quarterly for the house price index, I have to make a mean for every quarter

1. Check if the monthly data is an 'object' or 'datatime'

In [79]:
print(CBPR['Monthly'].dtype)

object

In [82]:
CBPR['Monthly'] = pd.to_datetime(CBPR['Monthly'])
print(CBPR['Monthly'].dtype)

datetime64[ns]

2. Now that is a datetime, I make the quarterly mean with the same quarters as the HPI table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

 - Add a new column that indicates which month is in which Quater

In [83]:
CBPR.loc[:, 'temp_quater'] = CBPR['Monthly'].dt.to_period('Q')

In [84]:
CBPR

           Country    Monthly  Interest Rate temp_quater
0        Argentina 2010-01-31           9.50      2010Q1
1        Argentina 2010-02-28           9.50      2010Q1
2        Argentina 2010-03-31           9.50      2010Q1
3        Argentina 2010-04-30           9.50      2010Q2
4        Argentina 2010-05-31           9.50      2010Q2
...            ...        ...            ...         ...
7113  South Africa 2025-08-31           7.00      2025Q3
7114  South Africa 2025-09-30           7.00      2025Q3
7115  South Africa 2025-10-31           7.00      2025Q4
7116  South Africa 2025-11-30           6.75      2025Q4
7117  South Africa 2025-12-31           6.75      2025Q4

[7118 rows x 4 columns]

In [88]:
CBPR = CBPR.groupby(['Country', 'temp_quater'])['Interest Rate'].mean().reset_index()
CBPR = CBPR.copy()
CBPR.loc[:, 'Quarter'] = CBPR['temp_quater'].dt.to_timestamp('Q')

In [89]:
CBPR

            Country temp_quater  Interest Rate    Quarter
0         Argentina      2010Q1       9.500000 2010-03-31
1         Argentina      2010Q2       9.500000 2010-06-30
2         Argentina      2010Q3       9.500000 2010-09-30
3         Argentina      2010Q4       9.500000 2010-12-31
4         Argentina      2011Q1       9.500000 2011-03-31
...             ...         ...            ...        ...
2369  United States      2024Q4       4.625000 2024-12-31
2370  United States      2025Q1       4.375000 2025-03-31
2371  United States      2025Q2       4.375000 2025-06-30
2372  United States      2025Q3       4.291667 2025-09-30
2373  United States      2025Q4       3.791667 2025-12-31

[2374 rows x 4 columns]

In [90]:
final_columns = ['Country', 'Quarter', 'Interest Rate'] 
CBPR_clean = CBPR[final_columns]

In [91]:
CBPR_clean

            Country    Quarter  Interest Rate
0         Argentina 2010-03-31       9.500000
1         Argentina 2010-06-30       9.500000
2         Argentina 2010-09-30       9.500000
3         Argentina 2010-12-31       9.500000
4         Argentina 2011-03-31       9.500000
...             ...        ...            ...
2369  United States 2024-12-31       4.625000
2370  United States 2025-03-31       4.375000
2371  United States 2025-06-30       4.375000
2372  United States 2025-09-30       4.291667
2373  United States 2025-12-31       3.791667

[2374 rows x 3 columns]

The country bank for Interest Rates:

The country bank for Interest Rates:

In [92]:
CBPR_countries = set (CBPR_clean['Country'].unique())
print(f"Total countries in Central Bank Policy Rates: {len(CBPR_countries)}")

Total countries in Central Bank Policy Rates: 40

# Data 3: Consumer prices

The consumer price index data set contains long series that track the overall change in the prices of goods and services purchased by households. Consumer price indices are a key macroeconomic indicator, for instance to measure inflation and assess purchasing power over time.

In [98]:
CPI_raw = pd.read_csv("raw_data/Consumer_prices_Yearly_change.csv", skiprows=5)#CPI_raw = Consumer prices index raw
CPI = CPI_raw[['REF_AREA:Reference area', 'TIME_PERIOD:Period','OBS_VALUE:Value']].copy()
CPI.columns = ['Country_Raw', 'Monthly', 'Change of inflation rate']

In [99]:
CPI

                   Country_Raw     Monthly  Change of inflation rate
0      AE:United Arab Emirates  2010-01-31                 -0.431897
1      AE:United Arab Emirates  2010-02-28                 -0.264243
2      AE:United Arab Emirates  2010-03-31                  0.682230
3      AE:United Arab Emirates  2010-04-30                  0.789923
4      AE:United Arab Emirates  2010-05-31                  0.876724
...                        ...         ...                       ...
12086          ZA:South Africa  2025-08-31                  3.303274
12087          ZA:South Africa  2025-09-30                  3.399981
12088          ZA:South Africa  2025-10-31                  3.603607
12089          ZA:South Africa  2025-11-30                  3.503496
12090          ZA:South Africa  2025-12-31                  3.600003

[12091 rows x 3 columns]

In [100]:
CPI['Country'] = CPI['Country_Raw'].str.split(':').str[1]
CPI = CPI[['Country', 'Monthly', 'Change of inflation rate']].copy()

The data for the consumer prices is monthly, but I need it in quarters

In [102]:
print(CPI['Monthly'].dtype)

object

2. It's an object so we change it to datetime

In [103]:
CPI['Monthly'] = pd.to_datetime(CPI['Monthly'])
print(CPI['Monthly'].dtype)

datetime64[ns]

4. Now that is a datetime, I make the quarterly mean with the same quarters as the HPI & CBPR table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

I insert a new column that indicates if the month belongs to Q1, Q2, Q3 or Q4

In [106]:
CPI.loc[:, 'temp_quater'] = CPI['Monthly'].dt.to_period('Q')

In [110]:
CPI = CPI.groupby(['Country', 'temp_quater'])['Change of inflation rate'].mean().reset_index()

In [111]:
CPI

            Country temp_quater  Change of inflation rate
0           Algeria      2010Q1                  4.323700
1           Algeria      2010Q2                  4.946776
2           Algeria      2010Q3                  3.465990
3           Algeria      2010Q4                  2.989893
4           Algeria      2011Q1                  3.495927
...             ...         ...                       ...
4027  United States      2024Q4                  2.745114
4028  United States      2025Q1                  2.737586
4029  United States      2025Q2                  2.445133
4030  United States      2025Q3                  2.877918
4031  United States      2025Q4                  2.706082

[4032 rows x 3 columns]

Now, let's make the temp_quarter column to look like the others (YYYY-03-31)

In [112]:
CPI.loc[:, 'Quarter'] = CPI['temp_quater'].dt.to_timestamp('Q')
final_columns = ['Country', 'Quarter', 'Change of inflation rate'] 
CPI_final = CPI[final_columns]

In [113]:
CPI_final

            Country    Quarter  Change of inflation rate
0           Algeria 2010-03-31                  4.323700
1           Algeria 2010-06-30                  4.946776
2           Algeria 2010-09-30                  3.465990
3           Algeria 2010-12-31                  2.989893
4           Algeria 2011-03-31                  3.495927
...             ...        ...                       ...
4027  United States 2024-12-31                  2.745114
4028  United States 2025-03-31                  2.737586
4029  United States 2025-06-30                  2.445133
4030  United States 2025-09-30                  2.877918
4031  United States 2025-12-31                  2.706082

[4032 rows x 3 columns]

The country name bank for Inflation Rate: