In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

# Housing trends through the lens of interest rates

Plan of action
1. Introduce & Hypothesis (introduce unemployement & GDP growth)
2. Load the cleaned data
3. EDA
4. Advancing vs Advanced ($H_2$)
5. Statistical Modeling (test $h_1$ and $h_2$)
6. Covid-19 factor
7. Limitations
8. Conclusions

## Introduction

Currently I am a 2nd year economics and finance student and last semester I had a very interesting course called "Money, banking and financial markets". 
The core of the course was to understand the role of the monetary policy as a tool to stabilize the economy.

We discussed a lot how central banks change the nominal interest rate to influence the demand for money. The banks generally do that when the inflation target is not equal to the real inflation.

#### The Economic Theory

To understand and analyze the relationship between interest rates and housing prices, we first must understand the **Monetary Transmission Mechanism**.

When there is high inflation that generally means that people have a lot of money on their hands and spend a lot. That causes prices of goods and services to rise. That is a signal that the economy is "overheating"  
To prevent inflation going higher, central banks raise their Policy rates (interest rates). As interest rates rise:  

**Cost of borrowing**: Borrowing money becomes more expensive, therefore reducing the demand for mortgages. As a result, less people get mortgages and less people are buying real estate. 

**Opportunity cost**: Savings accounts become more lucrative, which incentives people to save their money than to spend them on the economy and therefore real estate.

**"Policy rate" Assumption**:
In this project, when I mention the Interest rate, I am referring to the general sense used in economic theory. We assume that "Policy Rate" set by a Central Bank trickles down to all other types of rates.   
By using one rate, I am looking at the overall "price of money" in that country.

Even though, interest rates are important litmus test for the behavior of housing prices, they aren't the only factor. To isolate their magnitude, we must take into consideration other macroeconomic 'confounders'. I have chosen the following:  

**GDP Growth**:  The growth of a countries economy. The idea is that as an economy grows, so too does the housing demand  

**Unemployment**: Represents job security. High unemployment reduces the pool of eligible mortgage borrowers.

## Research problem

In class we studied the theoretical economic theory that explains the interest rates as tool to stabilize the economy, but this project will focus on the real-life application of the interest rate in terms of one of the most sought after social and material assets - residential real estate.

The core research questions, that I aim to answer:

1. **Global sensitivity to the effect**: Is there a universal significant inverse relationship between real interest rates and housing price growth on a global scale
2. **Economic Differences**: Is the sensitivity to the effect differs between "Developed" and "Developing" countries?

### Data used
### LAGS

## Hypothesis

### *$H_1$*:  There is a significant inverse relationship where higher rates lead to lower price growth

We will be testing whether there is a statistically significant inverse relation between real interest rates and house price growth on a global scale.

*The Null Hypothesis($H_0$)*:  
Interest rates have no effect on the housing prices behavior  
$$\beta_1 = 0$$

*The alternative Hypothesis ($H_1$)*:  
There is a significant inverse relationship where higher rates lead to lower price growth
$$\beta_1<0$$

Regression model:  
$$HPI\_Growth_{t} = \beta_0 + \beta_1(Real\_Rate_{t-k}) + \beta_2(GDP\_growth_{t}) + \beta_3(Unemployment\_rate_{t}) + \epsilon$$

##### ***Variables:***

$HPI\_Growth_{t}$ - Percentage change in the Real House Price Index  

$\beta_0$(Intercept) - The House price Growth if the Interest rates, GDP and Unemployment were to be all 0  

$\beta_1$ (Interest Rate Sensitivity) - shows how sensitive house prices are to interest rates  

$Real\_Rate_{t-k}$ - The real interest rate lagged by *k* quarters to account for market frictions  

$\beta_2$ (GDP Growth) - how much the growth of the Gross Domestic Product influences housing prices  

$\beta_3$(Unemployment) - how much a weakening labour market slows housing prices  

$GDP\_growth$ and $Unemployment\_rate$: Confounding variables included to isolate the specific impact of monetary policy.

### *$H_2$*: Sensitivity to the interest rate changes felt in the housing market in "Developed" countries is higher than in "Developing" countries

The Null Hypothesis ($H_0$):  
There is no difference in sensitivity between economy types ($\beta_4 = 0$).

The Alternative Hypothesis ($H_2$):  
Advanced economies show higher sensitivity to interest rate changes ($\beta_4 \neq 0$, specifically $\beta_4 < 0$ when **interacting** with the rate).

Interaction Model:$$HPI\_Growth = \beta_0 + \beta_1(Real\_Rate) + \beta_2(GDP) + \beta_3(Unemployment) + \beta_4(Real\_Rate \times Is\_Developed) + \epsilon$$

##### ***Variables:***

$HPI\_Growth_{t}$ - Percentage change in the Real House Price Index  

$\beta_0$(Intercept) - The House price Growth if the Interest rates, GDP and Unemployment were to be all 0  

$\beta_1$ (Interest Rate Sensitivity) - shows how sensitive house prices are to interest rates  

$Real\_Rate_{t-k}$ - The real interest rate lagged by *k* quarters to account for market frictions  

$\beta_2$ (GDP Growth) - how much the growth of the Gross Domestic Product influences housing prices  

$\beta_3$(Unemployment) - how much a weakening labour market slows housing prices  

$GDP\_growth$ and $Unemployment\_rate$: Confounding variables included to isolate the specific impact of monetary policy.  

$HPI\_Growth_{t}$ - Percentage change in the Real House Price Index  

$Real\_Rate_{t-k}$ - The real interest rate lagged by *k* quarters to account for market frictions  

$GDP\_growth$ and $Unemployment\_rate$: Confounding variables included to isolate the specific impact of monetary policy.  

$\beta_4(Real\_Rate \times Is\_Developed)$ - identifies if the "slope" or sensitivity of housing prices changes specifically for  developed vs developing countries

## Load cleaned data and Categorize countries

First we load the cleaned data from Data_prep

In [65]:
Project_Data = pd.read_csv('master_housing_data.csv')

In [66]:
Project_Data

,Country,Quarter,HPI_Growth,Real_Rate,GDP growth,Unemployment rate,Real_HPI,Nominal Interest Rate,Change of inflation rate
0,Australia,2011-03-31,-2.774982,1.493697,1.879672,4.967735,97.1941,4.750000,3.256303
1,Australia,2011-06-30,-5.556938,1.200939,2.472139,4.963181,95.6559,4.750000,3.549061
2,Australia,2011-09-30,-5.935166,1.330311,3.175238,5.195016,93.4029,4.750000,3.419689
3,Australia,2011-12-31,-6.842083,1.507224,3.455913,5.205014,92.6571,4.500000,2.992776
4,Australia,2012-03-31,-4.188526,2.622330,4.839548,5.141726,93.1231,4.250000,1.627670
...,...,...,...,...,...,...,...,...,...
1976,United States,2024-09-30,1.066657,2.586295,2.791390,4.166667,160.2521,5.208333,2.622039
1977,United States,2024-12-31,0.699312,1.879886,2.399788,4.133333,161.3926,4.625000,2.745114
1978,United States,2025-03-31,-0.122206,1.637414,2.019273,4.133333,159.9432,4.375000,2.737586
1979,United States,2025-06-30,-0.645120,1.929867,2.080467,4.200000,158.3531,4.375000,2.445133
1980,United States,2025-09-30,-1.609152,1.413749,2.335168,4.333333,157.6734,4.291667,2.877918

The data gathered and cleaned contains 1981 observations of global economies from 2010 to 2025. Let's understand every variable used in the analysis:  
1. **Country and Quarter**: Identify location and time in quarterly frequency of each observation 
2. **HPI_Growth**: The Year-on-Year percent change in real house prices. This is the primary metric we are trying to explain so it's our Dependent Variable - $Y$  
3. **Real Rate**: The cost of borrowing money, adjusted for inflation by using the Fisher Equation(Nominal Interest Rate - Inflation). This is our Independent Variable ($X$)  
4. **GDP growth**: The quarterly growth rate of the Gross Domestic Product. Serves as a Control Variable in this analysis as it account for the how wealthy people("wealth factor") and in general, the health on an economy  
5. **Unemployment rate**: The change of the *labour* force that does not have a job. This also serves as a Control Variable, as to account for the job security and mortgage eligibility.  
6. **Real_HPI**: The raw real housing price index, which tracks the value of *residential* properties that are adjusted for inflation and anchored to 2010 (2010 = 100). The base for growth calculations.  
7. **Nominal Interest Rate**: The central bank policy before adjusting for inflation  
8. **Change of inflation rate**: The consumer price index (CPI) data used to find the real interest rate from the nominal.

To test our hypothesis, we will need to categorize the already cleaned country data in Data_prep file into **Developed** and **Developing**

There are a lot of organizations that have those classifications based on different variables. I have based the grouping of the countries based on the International Monetary Fund Advanced Economy, because they base their groupings on 3 factors:
* GDP per Capita - the average income of standard of living
* Export Diversification - The IMF considers that if a country is rich, because of 1 export, then they potential crash is immense. Advanced economies have many different industries a.e diversified export
* Financial Integration - this variable measures how deeply the country's banking system is connected to the global one. This also includes currency stability and how easy is for foreigners to invest

This classification is appropriate for the analysis, as it captures structural economic differences that may influence how housing markets respond to interest rate changes.

Based on their [database](https://www.imf.org/en/publications/weo/weo-database/2023/october/groups-and-aggregates) here are the developed economies we will be working with:

In [67]:
developed_list = [
'Australia', 'Austria', 'Belgium', 'Canada', 'Czechia', 'Denmark', 
    'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Iceland', 
    'Ireland', 'Israel', 'Italy', 'Japan', 'Korea', 'Latvia', 
    'Lithuania', 'Luxembourg', 'Netherlands', 'New Zealand', 'Norway', 
    'Portugal', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 
    'United Kingdom', 'United States']

To test $H_2$ - the sensitivity of interest rates we also introduce a binary indicator:  
0: Developing economy  
1: Developed economy  

This variable is essential for the Interaction Term in the regression and will mathematically determine if price sensitivity is stronger in a certain economic setting.

In [68]:
#Adding new column Developed vs Developing
Project_Data['Class'] = np.where(Project_Data['Country'].isin(developed_list), 'Developed', 'Developing')
#Another column where Developed = 1 and Developing = 0
Project_Data['Class Numeric'] = Project_Data['Class'].map({'Developed': 1, 'Developing': 0})

In [69]:
Project_Data

,Country,Quarter,HPI_Growth,Real_Rate,GDP growth,Unemployment rate,Real_HPI,Nominal Interest Rate,Change of inflation rate,Class,Class Numeric
0,Australia,2011-03-31,-2.774982,1.493697,1.879672,4.967735,97.1941,4.750000,3.256303,Developed,1
1,Australia,2011-06-30,-5.556938,1.200939,2.472139,4.963181,95.6559,4.750000,3.549061,Developed,1
2,Australia,2011-09-30,-5.935166,1.330311,3.175238,5.195016,93.4029,4.750000,3.419689,Developed,1
3,Australia,2011-12-31,-6.842083,1.507224,3.455913,5.205014,92.6571,4.500000,2.992776,Developed,1
4,Australia,2012-03-31,-4.188526,2.622330,4.839548,5.141726,93.1231,4.250000,1.627670,Developed,1
...,...,...,...,...,...,...,...,...,...,...,...
1976,United States,2024-09-30,1.066657,2.586295,2.791390,4.166667,160.2521,5.208333,2.622039,Developed,1
1977,United States,2024-12-31,0.699312,1.879886,2.399788,4.133333,161.3926,4.625000,2.745114,Developed,1
1978,United States,2025-03-31,-0.122206,1.637414,2.019273,4.133333,159.9432,4.375000,2.737586,Developed,1
1979,United States,2025-06-30,-0.645120,1.929867,2.080467,4.200000,158.3531,4.375000,2.445133,Developed,1
1980,United States,2025-09-30,-1.609152,1.413749,2.335168,4.333333,157.6734,4.291667,2.877918,Developed,1

In [70]:
# to see how may of each group we have
country_counts = Project_Data.groupby('Class')['Country'].nunique()
observation_counts = Project_Data['Class']. value_counts()
#table
summary = pd.DataFrame({
    'Total Countries': country_counts,
    'Total Observations': observation_counts
})
print("Classification Summary:")
print(summary)

Classification Summary:
            Total Countries  Total Observations
Developed                30                1649
Developing                6                 332

In [71]:
all_countries = Project_Data['Country'].unique()

#  list that categorizes countries using developed_list
developed_in_data = [c for c in all_countries if c in developed_list]
developing_in_data = [c for c in all_countries if c not in developed_list]

#  Results and counts
print(f"Total Unique Countries: {len(all_countries)}")
print("-" * 30)
print(f" Developed ({len(developed_in_data)}):")
print(developed_in_data)

print("-" * 30)
print(f"Developing ({len(developing_in_data)}):")
print(developing_in_data)

Total Unique Countries: 36
------------------------------
 Developed (30):
['Australia', 'Austria', 'Belgium', 'Canada', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Japan', 'Korea', 'Latvia', 'Lithuania', 'Luxembourg', 'Netherlands', 'New Zealand', 'Norway', 'Portugal', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom', 'United States']
------------------------------
Developing (6):
['Chile', 'Colombia', 'Hungary', 'Mexico', 'Poland', 'Türkiye']

**Interpretation**  
The data that has survived the cleaning - meaning that there is data available for all variables for each country is biased towards Developed countries. That may be due to the stricter reporting standards of those countries. While yes, developed countries are a larger group (30), the developing countries of 6 provide data for countries from Latin America, Eastern Europe and the Middle East. That provides sufficient data to test for structural differences in the interest rate sensitivity.  
This will also be mentioned in the **Limitation** section of the analysis

In [ ]:
correlation = Project_Data['Real_Rate'].corr(df['HPI_Growth'])
print(f"Overall Correlation between Real Rates and HPI Growth: {correlation:.2f}")

### Scope and Assumptions: 
Developing countries don't always have the most reliant data. Those countries also have more recent data, so our scope will be in the 21st century (2010-2025)

### Limitations
Data for Developing nations can be less frequent or subject to revisions. Furthermore, my analysis assumes that central bank policy rates are a reliable proxy for mortgage market conditions.