In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Final project 
# The housing project

Introduction: 
Currently I am a 2nd year economics and finance student and last semester I had a very interesting course called "Money, banking and financial markets". In this course we talked a lot about how interest rates affect the world and how it works as a tool to make people spend more or less, whatever is best for the economy.

The idea is the following:
When there is high inflation that generally means that people have a lot of money on their hands and spend a lot. That causes prices of good and services to rise. To prevent inflation going higher, central banks raise their interest rates so people don't borrow as much. When interest rate go high, borrowing money becomes more expensive and people borrow less. This process aims to "cool down" the economy. 

That is in theory, but I was curious of how that effect is felt around the world as housing prices aren't all the same around the world. I also thought if there was a different affect for some countries and not others, if perhaps some are more reliant on mortgages than others.

This was a very interesting notion to me and in this project I aim to analyze how different interest rates and inflation rates affect the housing prices in developed and developing countries. 

Limitation: Developing countries don't always have the most reliant data. Those countries also have more recent data, so our scope will be in the 21st century.

# The hypothesis I go into this project are the following:

H1: Interest rates affect housing prices equally across countries

H2: The affect of interest rates is stronger in developed countries,than in developing countries

# The steps I aim to make for this project:

1. Gather and clean data about: Housing prices, Interest rates, Income levels and Inflation
2. Clean and merge them into 1 big data set
3. Divide data for developing and developed countries
4. Analyze trends per group over the years
5. Run a regression analysis on every group
6. Compare and Analyze - confirm or deny H1 AND H2
7. Summary of the project

# Data used:
When adding new data, I will be adding it here. If explanation is need about the data, it will be provided here.
1. Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))
- The data is 'real', which means it's adjusted for inflation - we only look at the real change for the period
- It uses 2010 as a base index = 100, so that means if in 2008 the data shows 74, that means that it's 74% of the price that it would be in 2010

# DATA: Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))

Looking at the data in excel, there are 7 rows that explain the file FREQ:Frequency, Unit of measure,Value, Year and Topic-The metadata.
To read the file, I skip the first 7 rows:

In [60]:
HPI = pd.read_csv("Housing_price_index_real.csv", skiprows=7)

In [61]:
HPI

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,VALUE:Value,UNIT_MEASURE:Unit of measure,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2007-12-31,F:Free,NaN,A:Normal value,95.7745
1,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-03-31,F:Free,NaN,A:Normal value,95.0590
2,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-06-30,F:Free,NaN,A:Normal value,95.3475
3,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-09-30,F:Free,NaN,A:Normal value,95.6345
4,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-12-31,F:Free,NaN,A:Normal value,95.3757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5750,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2024-12-31,F:Free,NaN,A:Normal value,87.9349
5751,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-03-31,F:Free,NaN,A:Normal value,87.9561
5752,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-06-30,F:Free,NaN,A:Normal value,88.0077
5753,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-09-30,F:Free,NaN,A:Normal value,88.3881
5754,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-12-31,F:Free,NaN,A:Normal value,89.4681

For my analysis I need only a few columns: Reference Area (Country), Period (Date) and Observation Value (Price)

In [62]:
needed_columns = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
HPI = HPI[needed_columns]

In [63]:
HPI

,REF_AREA:Reference area,TIME_PERIOD:Period,OBS_VALUE:Value
0,4T:Emerging market economies (aggregate),2007-12-31,95.7745
1,4T:Emerging market economies (aggregate),2008-03-31,95.0590
2,4T:Emerging market economies (aggregate),2008-06-30,95.3475
3,4T:Emerging market economies (aggregate),2008-09-30,95.6345
4,4T:Emerging market economies (aggregate),2008-12-31,95.3757
...,...,...,...
5750,ZA:South Africa,2024-12-31,87.9349
5751,ZA:South Africa,2025-03-31,87.9561
5752,ZA:South Africa,2025-06-30,88.0077
5753,ZA:South Africa,2025-09-30,88.3881
5754,ZA:South Africa,2025-12-31,89.4681

The names of these columns need to be renamed for reading purposes

In [64]:
HPI.columns = ['Country_Raw', 'Quarter', 'Real Price Index']

In [65]:
HPI

                                   Country_Raw     Quarter  Real Price Index
0     4T:Emerging market economies (aggregate)  2007-12-31           95.7745
1     4T:Emerging market economies (aggregate)  2008-03-31           95.0590
2     4T:Emerging market economies (aggregate)  2008-06-30           95.3475
3     4T:Emerging market economies (aggregate)  2008-09-30           95.6345
4     4T:Emerging market economies (aggregate)  2008-12-31           95.3757
...                                        ...         ...               ...
5750                           ZA:South Africa  2024-12-31           87.9349
5751                           ZA:South Africa  2025-03-31           87.9561
5752                           ZA:South Africa  2025-06-30           88.0077
5753                           ZA:South Africa  2025-09-30           88.3881
5754                           ZA:South Africa  2025-12-31           89.4681

[5755 rows x 3 columns]

As we can see, the country_raw column has both aggregate data and country codes which we need to remove

1. Let's remove the Aggregate data

- Let's try doing it with a mask (I will make group of what data I don't want to included, then with the ~ sign I'll remove it)

In [71]:
mask = HPI['Country_Raw'].str.contains('aggregate|economies|World|area', case=False)
HPI = HPI[~mask]

In [72]:
HPI

          Country_Raw     Quarter  Real Price Index
144        AT:Austria  2000-03-31           98.2843
145        AT:Austria  2000-06-30           95.9464
146        AT:Austria  2000-09-30           93.7325
147        AT:Austria  2000-12-31           92.7328
148        AT:Austria  2001-03-31           96.5591
...               ...         ...               ...
5750  ZA:South Africa  2024-12-31           87.9349
5751  ZA:South Africa  2025-03-31           87.9561
5752  ZA:South Africa  2025-06-30           88.0077
5753  ZA:South Africa  2025-09-30           88.3881
5754  ZA:South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

- Now I have to remove the country code

In [77]:
HPI['Country_Raw'].str.split(':').str[1]

144          Austria
145          Austria
146          Austria
147          Austria
148          Austria
            ...
5750    South Africa
5751    South Africa
5752    South Africa
5753    South Africa
5754    South Africa
Name: Country_Raw, Length: 5436, dtype: object

In [80]:
HPI['Country'] = HPI['Country_Raw'].str.split(':').str[1]

In [81]:
HPI

          Country_Raw     Quarter  Real Price Index       Country
144        AT:Austria  2000-03-31           98.2843       Austria
145        AT:Austria  2000-06-30           95.9464       Austria
146        AT:Austria  2000-09-30           93.7325       Austria
147        AT:Austria  2000-12-31           92.7328       Austria
148        AT:Austria  2001-03-31           96.5591       Austria
...               ...         ...               ...           ...
5750  ZA:South Africa  2024-12-31           87.9349  South Africa
5751  ZA:South Africa  2025-03-31           87.9561  South Africa
5752  ZA:South Africa  2025-06-30           88.0077  South Africa
5753  ZA:South Africa  2025-09-30           88.3881  South Africa
5754  ZA:South Africa  2025-12-31           89.4681  South Africa

[5436 rows x 4 columns]