In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Final project 
# The housing project

Introduction: 
Currently I am a 2nd year economics and finance student and last semester I had a very interesting course called "Money, banking and financial markets". In this course we talked a lot about how interest rates affect the world and how it works as a tool to make people spend more or less, whatever is best for the economy.

The idea is the following:
When there is high inflation that generally means that people have a lot of money on their hands and spend a lot. That causes prices of good and services to rise. To prevent inflation going higher, central banks raise their interest rates so people don't borrow as much. When interest rate go high, borrowing money becomes more expensive and people borrow less. This process aims to "cool down" the economy. 

That is in theory, but I was curious of how that effect is felt around the world as housing prices aren't all the same around the world. I also thought if there was a different affect for some countries and not others, if perhaps some are more reliant on mortgages than others.

This was a very interesting notion to me and in this project I aim to analyze how different interest rates and inflation rates affect the housing prices in developed and developing countries. 

Limitation: Developing countries don't always have the most reliant data. Those countries also have more recent data, so our scope will be in the 21st century.

# The hypothesis I go into this project are the following:

H1: Interest rates affect housing prices equally across countries

H2: The affect of interest rates is stronger in developed countries,than in developing countries

# The steps I aim to make for this project:

1. Gather and clean data about: Housing prices, Interest rates, Income levels and Inflation
2. Clean and merge them into 1 big data set
3. Divide data for developing and developed countries
4. Analyze trends per group over the years
5. Run a regression analysis on every group
6. Compare and Analyze - confirm or deny H1 AND H2
7. Summary of the project

# Data used:
When adding new data, I will be adding it here. If explanation is need about the data, it will be provided here.
1. Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))
- The data is 'real', which means it's adjusted for inflation - we only look at the real change for the period
- It uses 2010 as a base index = 100, so that means if in 2008 the data shows 74, that means that it's 74% of the price that it would be in 2010

# DATA: Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))

Looking at the data in excel, there are 7 rows that explain the file FREQ:Frequency, Unit of measure,Value, Year and Topic-The metadata.
To read the file, I skip the first 7 rows:

In [29]:
HPI = pd.read_csv("Housing_price_index_real.csv", skiprows=7)

In [30]:
HPI

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,VALUE:Value,UNIT_MEASURE:Unit of measure,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2007-12-31,F:Free,NaN,A:Normal value,95.7745
1,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-03-31,F:Free,NaN,A:Normal value,95.0590
2,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-06-30,F:Free,NaN,A:Normal value,95.3475
3,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-09-30,F:Free,NaN,A:Normal value,95.6345
4,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-12-31,F:Free,NaN,A:Normal value,95.3757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5750,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2024-12-31,F:Free,NaN,A:Normal value,87.9349
5751,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-03-31,F:Free,NaN,A:Normal value,87.9561
5752,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-06-30,F:Free,NaN,A:Normal value,88.0077
5753,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-09-30,F:Free,NaN,A:Normal value,88.3881
5754,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-12-31,F:Free,NaN,A:Normal value,89.4681

For my analysis I need only a few columns: Reference Area (Country), Period (Date) and Observation Value (Price)

In [31]:
needed_columns = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
HPI = HPI[needed_columns]

In [32]:
HPI

,REF_AREA:Reference area,TIME_PERIOD:Period,OBS_VALUE:Value
0,4T:Emerging market economies (aggregate),2007-12-31,95.7745
1,4T:Emerging market economies (aggregate),2008-03-31,95.0590
2,4T:Emerging market economies (aggregate),2008-06-30,95.3475
3,4T:Emerging market economies (aggregate),2008-09-30,95.6345
4,4T:Emerging market economies (aggregate),2008-12-31,95.3757
...,...,...,...
5750,ZA:South Africa,2024-12-31,87.9349
5751,ZA:South Africa,2025-03-31,87.9561
5752,ZA:South Africa,2025-06-30,88.0077
5753,ZA:South Africa,2025-09-30,88.3881
5754,ZA:South Africa,2025-12-31,89.4681

The names of these columns need to be renamed for reading purposes

In [33]:
HPI.columns = ['Country_Raw', 'Quarter', 'Real Price Index']

In [34]:
HPI

                                   Country_Raw     Quarter  Real Price Index
0     4T:Emerging market economies (aggregate)  2007-12-31           95.7745
1     4T:Emerging market economies (aggregate)  2008-03-31           95.0590
2     4T:Emerging market economies (aggregate)  2008-06-30           95.3475
3     4T:Emerging market economies (aggregate)  2008-09-30           95.6345
4     4T:Emerging market economies (aggregate)  2008-12-31           95.3757
...                                        ...         ...               ...
5750                           ZA:South Africa  2024-12-31           87.9349
5751                           ZA:South Africa  2025-03-31           87.9561
5752                           ZA:South Africa  2025-06-30           88.0077
5753                           ZA:South Africa  2025-09-30           88.3881
5754                           ZA:South Africa  2025-12-31           89.4681

[5755 rows x 3 columns]

As we can see, the country_raw column has both aggregate data and country codes which we need to remove

1. Let's remove the Aggregate data

- Let's try doing it with a mask (I will make group of what data I don't want to included, then with the ~ sign I'll remove it)

In [35]:
mask = HPI['Country_Raw'].str.contains('aggregate|economies|World|area', case=False)
HPI = HPI[~mask]

In [36]:
HPI

          Country_Raw     Quarter  Real Price Index
144        AT:Austria  2000-03-31           98.2843
145        AT:Austria  2000-06-30           95.9464
146        AT:Austria  2000-09-30           93.7325
147        AT:Austria  2000-12-31           92.7328
148        AT:Austria  2001-03-31           96.5591
...               ...         ...               ...
5750  ZA:South Africa  2024-12-31           87.9349
5751  ZA:South Africa  2025-03-31           87.9561
5752  ZA:South Africa  2025-06-30           88.0077
5753  ZA:South Africa  2025-09-30           88.3881
5754  ZA:South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

- Now I have to remove the country code

In [37]:
HPI['Country_Raw'].str.split(':').str[1]

144          Austria
145          Austria
146          Austria
147          Austria
148          Austria
            ...
5750    South Africa
5751    South Africa
5752    South Africa
5753    South Africa
5754    South Africa
Name: Country_Raw, Length: 5436, dtype: object

In [39]:
HPI.loc[:, 'Country'] = HPI['Country_Raw'].str.split(':').str[1]

In [40]:
HPI

          Country_Raw     Quarter  Real Price Index       Country
144        AT:Austria  2000-03-31           98.2843       Austria
145        AT:Austria  2000-06-30           95.9464       Austria
146        AT:Austria  2000-09-30           93.7325       Austria
147        AT:Austria  2000-12-31           92.7328       Austria
148        AT:Austria  2001-03-31           96.5591       Austria
...               ...         ...               ...           ...
5750  ZA:South Africa  2024-12-31           87.9349  South Africa
5751  ZA:South Africa  2025-03-31           87.9561  South Africa
5752  ZA:South Africa  2025-06-30           88.0077  South Africa
5753  ZA:South Africa  2025-09-30           88.3881  South Africa
5754  ZA:South Africa  2025-12-31           89.4681  South Africa

[5436 rows x 4 columns]

In [47]:
HPI_c = HPI[['Country', 'Quarter', 'Real Price Index']] # HPC_c= Housing Price index clean

In [48]:
HPI_c

           Country    Quarter  Real Price Index
144        Austria 2000-03-31           98.2843
145        Austria 2000-06-30           95.9464
146        Austria 2000-09-30           93.7325
147        Austria 2000-12-31           92.7328
148        Austria 2001-03-31           96.5591
...            ...        ...               ...
5750  South Africa 2024-12-31           87.9349
5751  South Africa 2025-03-31           87.9561
5752  South Africa 2025-06-30           88.0077
5753  South Africa 2025-09-30           88.3881
5754  South Africa 2025-12-31           89.4681

[5436 rows x 3 columns]

Now we have the clean version of the table - only contains clean country data

In [49]:
print(HPI_c['Country'].unique()) # I wan to to see with which countries I'm working with and check which fall into what group

['Austria' 'Australia' 'Belgium' 'Bulgaria' 'Brazil' 'Canada'
 'Switzerland' 'Chile' 'China' 'Colombia' 'Cyprus' 'Czechia' 'Germany'
 'Denmark' 'Estonia' 'Spain' 'Finland' 'France' 'United Kingdom' 'Greece'
 'Hong Kong SAR' 'Croatia' 'Hungary' 'Indonesia' 'Ireland' 'Israel'
 'India' 'Iceland' 'Italy' 'Japan' 'Korea' 'Lithuania' 'Luxembourg'
 'Latvia' 'Morocco' 'North Macedonia' 'Malta' 'Mexico' 'Malaysia'
 'Netherlands' 'Norway' 'New Zealand' 'Peru' 'Philippines' 'Poland'
 'Portugal' 'Romania' 'Serbia' 'Russia' 'Sweden' 'Singapore' 'Slovenia'
 'Slovakia' 'Thailand' 'Türkiye' 'United States' 'South Africa']

Looking at the data, not all countries have data from 2000 onwards;the data is already in chronicological order so I won't be sorting it

I decide to look when is the first entry for each country to find an idea of when to start the data

In [50]:
first_entries = HPI_c.groupby('Country').first()
print(first_entries)

                   Quarter  Real Price Index
Country
Australia       2000-03-31           55.9766
Austria         2000-03-31           98.2843
Belgium         2000-03-31           66.7303
Brazil          2001-03-31           52.2932
Bulgaria        2000-03-31           59.6427
Canada          2000-03-31           60.0711
Chile           2002-03-31           73.3761
China           2005-06-30           87.9500
Colombia        2000-03-31           76.9397
Croatia         2000-03-31           74.2766
Cyprus          2002-03-31           55.2744
Czechia         2008-03-31          105.4167
Denmark         2000-03-31           72.6628
Estonia         2005-03-31          101.9719
Finland         2000-03-31           73.7069
France          2000-03-31           57.0587
Germany         2000-03-31          118.7491
Greece          2000-03-31           77.6642
Hong Kong SAR   2000-03-31           66.4739
Hungary         2000-03-31           82.1241
Iceland         2000-03-31           85.0683
India           2009-03-31           88.9013
Indonesia       2002-03-31          139.3968
Ireland         2000-03-31           94.4460
Israel          2000-03-31           92.3658
Italy           2000-03-31           76.3039
Japan           2000-03-31          141.4415
Korea           2000-03-31           82.5668
Latvia          2006-03-31          149.2465
Lithuania       2000-03-31           41.9676
Luxembourg      2007-03-31           97.3951
Malaysia        2000-03-31           86.2324
Malta           2005-03-31           70.9393
Mexico          2005-03-31           90.9971
Morocco         2007-03-31          102.5356
Netherlands     2000-03-31           84.0758
New Zealand     2000-03-31           62.5862
North Macedonia 2000-03-31           72.7104
Norway          2000-03-31           62.6810
Peru            2000-03-31           83.5080
Philippines     2008-03-31          107.8330
Poland          2010-03-31          100.0602
Portugal        2000-03-31          118.7076
Romania         2009-03-31          119.3204
Russia          2001-03-31           34.9443
Serbia          2000-03-31          135.2788
Singapore       2000-03-31           87.8241
Slovakia        2006-03-31           82.1598
Slovenia        2007-03-31          110.1683
South Africa    2000-03-31           56.8608
Spain           2000-03-31           59.2993
Sweden          2000-03-31           53.3734
Switzerland     2000-03-31           77.5257
Thailand        2000-03-31           96.8028
Türkiye         2010-03-31           98.6380
United Kingdom  2000-03-31           62.6002
United States   2000-03-31           95.1841

The latest start is 2010-03-31, so I will start from then

In [55]:
print(HPI_c['Quarter'].dtype)

datetime64[ns]

To remove any data before 2010:

In [56]:
HPI_c = HPI_c[HPI_c['Quarter'] >= '2010-01-01'].copy()

In [57]:
HPI_c

           Country    Quarter  Real Price Index
184        Austria 2010-03-31          100.2528
185        Austria 2010-06-30           99.5266
186        Austria 2010-09-30           99.7640
187        Austria 2010-12-31          100.4564
188        Austria 2011-03-31          101.9770
...            ...        ...               ...
5750  South Africa 2024-12-31           87.9349
5751  South Africa 2025-03-31           87.9561
5752  South Africa 2025-06-30           88.0077
5753  South Africa 2025-09-30           88.3881
5754  South Africa 2025-12-31           89.4681

[3617 rows x 3 columns]

To check if I did it correctly

In [79]:
first_entries = HPI_c.groupby('Country').first()
print(first_entries)

                   Quarter  Real Price Index Economy_Type
Country
Australia       2010-03-31           99.9682     Advanced
Austria         2010-03-31          100.2528     Advanced
Belgium         2010-03-31           99.4178     Advanced
Brazil          2010-03-31           93.9314      Growing
Bulgaria        2010-03-31          102.5328      Growing
Canada          2010-03-31          100.2438     Advanced
Chile           2010-03-31           97.1334      Growing
China           2010-03-31           98.4735      Growing
Colombia        2010-03-31           97.9763      Growing
Croatia         2010-03-31          102.0834      Growing
Cyprus          2010-03-31          101.9884      Growing
Czechia         2010-03-31          100.4567      Growing
Denmark         2010-03-31           99.1487     Advanced
Estonia         2010-03-31          100.4538      Growing
Finland         2010-03-31           99.6381     Advanced
France          2010-03-31           97.5617     Advanced
Germany         2010-03-31           99.1342     Advanced
Greece          2010-03-31          106.2279     Advanced
Hong Kong SAR   2010-03-31           93.4491     Advanced
Hungary         2010-03-31          102.6162      Growing
Iceland         2010-03-31           99.2311     Advanced
India           2010-03-31           96.2271      Growing
Indonesia       2010-03-31          101.1526      Growing
Ireland         2010-03-31          106.1786     Advanced
Israel          2010-03-31           96.7735     Advanced
Italy           2010-03-31           99.6538     Advanced
Japan           2010-03-31           99.4510     Advanced
Korea           2010-03-31          100.4909     Advanced
Latvia          2010-03-31           98.8298      Growing
Lithuania       2010-03-31           99.1576      Growing
Luxembourg      2010-03-31          101.2382     Advanced
Malaysia        2010-03-31           96.8586      Growing
Malta           2010-03-31          101.9142      Growing
Mexico          2010-03-31           98.8179      Growing
Morocco         2010-03-31          100.5363      Growing
Netherlands     2010-03-31          101.0173     Advanced
New Zealand     2010-03-31          102.4238     Advanced
North Macedonia 2010-03-31          100.5580      Growing
Norway          2010-03-31           97.8581     Advanced
Peru            2010-03-31           95.7671      Growing
Philippines     2010-03-31           99.6264      Growing
Poland          2010-03-31          100.0602      Growing
Portugal        2010-03-31          101.6861     Advanced
Romania         2010-03-31          106.3460      Growing
Russia          2010-03-31          101.6916      Growing
Serbia          2010-03-31           99.0219      Growing
Singapore       2010-03-31           95.7487     Advanced
Slovakia        2010-03-31          101.2206      Growing
Slovenia        2010-03-31          101.6593      Growing
South Africa    2010-03-31          100.2246      Growing
Spain           2010-03-31          101.3059     Advanced
Sweden          2010-03-31           98.6638     Advanced
Switzerland     2010-03-31           98.3530     Advanced
Thailand        2010-03-31           99.1453      Growing
Türkiye         2010-03-31           98.6380      Growing
United Kingdom  2010-03-31           99.7592     Advanced
United States   2010-03-31          101.5333     Advanced

In [80]:
HPI_c

           Country    Quarter  Real Price Index Economy_Type
184        Austria 2010-03-31          100.2528     Advanced
185        Austria 2010-06-30           99.5266     Advanced
186        Austria 2010-09-30           99.7640     Advanced
187        Austria 2010-12-31          100.4564     Advanced
188        Austria 2011-03-31          101.9770     Advanced
...            ...        ...               ...          ...
5750  South Africa 2024-12-31           87.9349      Growing
5751  South Africa 2025-03-31           87.9561      Growing
5752  South Africa 2025-06-30           88.0077      Growing
5753  South Africa 2025-09-30           88.3881      Growing
5754  South Africa 2025-12-31           89.4681      Growing

[3617 rows x 4 columns]

According to the IMF (International money fund), since 2010 Croatia has graduated to becoming a "Developed economy"
in 2024

So should Croatia be considered an emerging or developed country?

Croatia will be considered as an "Emerging economy" as

1. The HPI is anchored to 2010

2. Croatia became a developed country in 2024, so for the majority of the time it behaved as an Emerging economy

Let's start grouping countries based on their status as of 2010:

In [81]:
developed_eco = [
    'Australia', 'Austria', 'Belgium', 'Canada', 'Denmark', 'Finland', 
    'France', 'Germany', 'Greece', 'Hong Kong SAR', 'Iceland', 'Ireland', 
    'Israel', 'Italy', 'Japan', 'Korea', 'Luxembourg', 'Netherlands', 
    'New Zealand', 'Norway', 'Portugal', 'Singapore', 'Spain', 'Sweden', 
    'Switzerland', 'United Kingdom', 'United States'
]

In [82]:
HPI_c['Economy_Type'] = HPI_c['Country'].apply(
        lambda x: 'Advanced' if x in developed_eco else 'Growing'
)

In [83]:
HPI_c

           Country    Quarter  Real Price Index Economy_Type
184        Austria 2010-03-31          100.2528     Advanced
185        Austria 2010-06-30           99.5266     Advanced
186        Austria 2010-09-30           99.7640     Advanced
187        Austria 2010-12-31          100.4564     Advanced
188        Austria 2011-03-31          101.9770     Advanced
...            ...        ...               ...          ...
5750  South Africa 2024-12-31           87.9349      Growing
5751  South Africa 2025-03-31           87.9561      Growing
5752  South Africa 2025-06-30           88.0077      Growing
5753  South Africa 2025-09-30           88.3881      Growing
5754  South Africa 2025-12-31           89.4681      Growing

[3617 rows x 4 columns]

In [84]:
HPI_grouped = HPI_c.groupby(['Quarter', 'Economy_Type'])['Real Price Index'].mean().reset_index()

In [85]:
HPI_grouped

       Quarter Economy_Type  Real Price Index
0   2010-03-31     Advanced         99.866985
1   2010-03-31      Growing         99.836633
2   2010-06-30     Advanced         99.986937
3   2010-06-30      Growing        100.016910
4   2010-09-30     Advanced        100.337519
..         ...          ...               ...
123 2025-06-30      Growing        136.566800
124 2025-09-30     Advanced        132.038170
125 2025-09-30      Growing        137.433153
126 2025-12-31     Advanced        138.770836
127 2025-12-31      Growing        134.501873

[128 rows x 3 columns]

Data 2: The central Banks policy rates

In [139]:
CB_rates = pd.read_csv("Central_bank_policy_rates.csv", skiprows=5)

In [140]:
CB_rates

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-01-31,F:Free,NaN,A:Normal value,9.50
1,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-02-28,F:Free,NaN,A:Normal value,9.50
2,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-03-31,F:Free,NaN,A:Normal value,9.50
3,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-04-30,F:Free,NaN,A:Normal value,9.50
4,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-05-31,F:Free,NaN,A:Normal value,9.50
...,...,...,...,...,...,...,...,...,...,...,...
7113,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-08-31,F:Free,NaN,A:Normal value,7.00
7114,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-09-30,F:Free,NaN,A:Normal value,7.00
7115,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-10-31,F:Free,NaN,A:Normal value,7.00
7116,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-11-30,F:Free,NaN,A:Normal value,6.75
7117,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-12-31,F:Free,NaN,A:Normal value,6.75

For my analysis I need only a few columns: Reference Area (Country), Period (Date) and Observation Value (Price)

In [141]:
needed_columns = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
CB_clean = CB_rates[needed_columns]

In [142]:
CB_clean

     REF_AREA:Reference area TIME_PERIOD:Period  OBS_VALUE:Value
0               AR:Argentina         2010-01-31             9.50
1               AR:Argentina         2010-02-28             9.50
2               AR:Argentina         2010-03-31             9.50
3               AR:Argentina         2010-04-30             9.50
4               AR:Argentina         2010-05-31             9.50
...                      ...                ...              ...
7113         ZA:South Africa         2025-08-31             7.00
7114         ZA:South Africa         2025-09-30             7.00
7115         ZA:South Africa         2025-10-31             7.00
7116         ZA:South Africa         2025-11-30             6.75
7117         ZA:South Africa         2025-12-31             6.75

[7118 rows x 3 columns]

Next, we need to rename the columns

In [146]:
CB_clean.columns = ['Country_Raw', 'Monthly', 'Nominal Price Index']

In [147]:
CB_clean

          Country_Raw     Monthly  Nominal Price Index
0        AR:Argentina  2010-01-31                 9.50
1        AR:Argentina  2010-02-28                 9.50
2        AR:Argentina  2010-03-31                 9.50
3        AR:Argentina  2010-04-30                 9.50
4        AR:Argentina  2010-05-31                 9.50
...               ...         ...                  ...
7113  ZA:South Africa  2025-08-31                 7.00
7114  ZA:South Africa  2025-09-30                 7.00
7115  ZA:South Africa  2025-10-31                 7.00
7116  ZA:South Africa  2025-11-30                 6.75
7117  ZA:South Africa  2025-12-31                 6.75

[7118 rows x 3 columns]

We need to remove the country code

In [152]:
CB_clean.loc[:, 'Country'] = CB_clean['Country_Raw'].str.split(':').str[1]

In [153]:
CB_clean

          Country_Raw     Monthly  Nominal Price Index       Country
0        AR:Argentina  2010-01-31                 9.50     Argentina
1        AR:Argentina  2010-02-28                 9.50     Argentina
2        AR:Argentina  2010-03-31                 9.50     Argentina
3        AR:Argentina  2010-04-30                 9.50     Argentina
4        AR:Argentina  2010-05-31                 9.50     Argentina
...               ...         ...                  ...           ...
7113  ZA:South Africa  2025-08-31                 7.00  South Africa
7114  ZA:South Africa  2025-09-30                 7.00  South Africa
7115  ZA:South Africa  2025-10-31                 7.00  South Africa
7116  ZA:South Africa  2025-11-30                 6.75  South Africa
7117  ZA:South Africa  2025-12-31                 6.75  South Africa

[7118 rows x 4 columns]

In [150]:
CBPR_clean = CB_clean[['Country', 'Monthly', 'Nominal Price Index']] # CBPR_clean= Central Bank policy rate clean

In [151]:
CBPR_clean

           Country     Monthly  Nominal Price Index
0        Argentina  2010-01-31                 9.50
1        Argentina  2010-02-28                 9.50
2        Argentina  2010-03-31                 9.50
3        Argentina  2010-04-30                 9.50
4        Argentina  2010-05-31                 9.50
...            ...         ...                  ...
7113  South Africa  2025-08-31                 7.00
7114  South Africa  2025-09-30                 7.00
7115  South Africa  2025-10-31                 7.00
7116  South Africa  2025-11-30                 6.75
7117  South Africa  2025-12-31                 6.75

[7118 rows x 3 columns]

In [154]:
print(CBPR_clean['Monthly'].dtype)

object