In [253]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Final project 
# The housing project

Introduction: 
Currently I am a 2nd year economics and finance student and last semester I had a very interesting course called "Money, banking and financial markets". In this course we talked a lot about how interest rates affect the world and how it works as a tool to make people spend more or less, whatever is best for the economy.

The idea is the following:
When there is high inflation that generally means that people have a lot of money on their hands and spend a lot. That causes prices of goods and services to rise. To prevent inflation going higher, central banks raise their interest rates so people don't borrow as much. When interest rate go high, borrowing money becomes more expensive and people borrow less. This process aims to "cool down" the economy. 

That is in theory, but I was curious of how that effect is felt around the world as housing prices aren't all the same around the world. I also thought if there was a different affect for some countries and not others, if perhaps some are more reliant on mortgages than others.

This was a very interesting notion to me and in this project I aim to analyze how different interest rates and inflation rates affect the housing prices in developed and developing countries. 

Limitation: Developing countries don't always have the most reliant data. Those countries also have more recent data, so our scope will be in the 21st century.

# The hypothesis I go into this project are the following:

H1: Interest rates affect housing prices equally across countries

H2: The affect of interest rates is stronger in developed countries,than in developing countries

# The steps I aim to make for this project:

1. Gather and clean data about: Housing prices, Interest rates, Income levels and Inflation
2. Clean and merge them into 1 big data set
3. Divide data for developing and developed countries
4. Analyze trends per group over the years
5. Run a regression analysis on every group
6. Compare and Analyze - confirm or deny H1 AND H2
7. Summary of the project

# Data used:
When adding new data, I will be adding it here. If explanation is need about the data, it will be provided here.
1. Residential property prices - index , real(adjusted for inflation) , 2000 - 2025, quarterly ([Bis.data.org](https://data.bis.org/topics/RPP/data?data_view=table&rows=REF_AREA&cols=TIME_PERIOD&settings=asc%7Cdesc%7Cname&filter=FREQ%3DQ%255EUNIT_MEASURE%3D628%255EVALUE%3DR%255EYEAR%3D2000%257C2001%257C2002%257C2003%257C2004%257C2005%257C2006%257C2007%257C2008%257C2009%257C2010%257C2011%257C2012%257C2013%257C2014%257C2015%257C2016%257C2017%257C2018%257C2019%257C2021%257C2020%257C2022%257C2025%257C2024%257C2023))
- The data is 'real', which means it's adjusted for inflation - we only look at the real change for the period
- It uses 2010 as a base index = 100, so that means if in 2008 the data shows 74, that means that it's 74% of the price that it would be in 2010

# DATA 1: Residential property prices - index , real(adjusted for inflation)

Looking at the data in excel, there are 7 rows that explain the file FREQ:Frequency, Unit of measure,Value, Year and Topic-The metadata.
To read the file, I skip the first 7 rows:

In [254]:
HPI = pd.read_csv("Housing_price_index_real.csv", skiprows=7)

In [255]:
HPI

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,VALUE:Value,UNIT_MEASURE:Unit of measure,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2007-12-31,F:Free,NaN,A:Normal value,95.7745
1,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-03-31,F:Free,NaN,A:Normal value,95.0590
2,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-06-30,F:Free,NaN,A:Normal value,95.3475
3,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-09-30,F:Free,NaN,A:Normal value,95.6345
4,"BIS,WS_SPP,1.0",Q.4T.R.628,Q:Quarterly,4T:Emerging market economies (aggregate),R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2008-12-31,F:Free,NaN,A:Normal value,95.3757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5750,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2024-12-31,F:Free,NaN,A:Normal value,87.9349
5751,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-03-31,F:Free,NaN,A:Normal value,87.9561
5752,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-06-30,F:Free,NaN,A:Normal value,88.0077
5753,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-09-30,F:Free,NaN,A:Normal value,88.3881
5754,"BIS,WS_SPP,1.0",Q.ZA.R.628,Q:Quarterly,ZA:South Africa,R:Real,"628:Index, 2010 = 100","Index, 2010 = 100",Units,2025-12-31,F:Free,NaN,A:Normal value,89.4681

For my analysis I need only a few columns: Reference Area (Country), Period (Date) and Observation Value (Price)

In [256]:
needed_columns = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
HPI = HPI[needed_columns]

In [265]:
HPI

          Country_Raw     Quarter  Real Price Index
144        AT:Austria  2000-03-31           98.2843
145        AT:Austria  2000-06-30           95.9464
146        AT:Austria  2000-09-30           93.7325
147        AT:Austria  2000-12-31           92.7328
148        AT:Austria  2001-03-31           96.5591
...               ...         ...               ...
5750  ZA:South Africa  2024-12-31           87.9349
5751  ZA:South Africa  2025-03-31           87.9561
5752  ZA:South Africa  2025-06-30           88.0077
5753  ZA:South Africa  2025-09-30           88.3881
5754  ZA:South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

The names of these columns need to be renamed for reading purposes

In [266]:
HPI.columns = ['Country_Raw', 'Quarter', 'Real Price Index']

In [267]:
HPI

          Country_Raw     Quarter  Real Price Index
144        AT:Austria  2000-03-31           98.2843
145        AT:Austria  2000-06-30           95.9464
146        AT:Austria  2000-09-30           93.7325
147        AT:Austria  2000-12-31           92.7328
148        AT:Austria  2001-03-31           96.5591
...               ...         ...               ...
5750  ZA:South Africa  2024-12-31           87.9349
5751  ZA:South Africa  2025-03-31           87.9561
5752  ZA:South Africa  2025-06-30           88.0077
5753  ZA:South Africa  2025-09-30           88.3881
5754  ZA:South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

As we can see, the country_raw column has both aggregate data and country codes which we need to remove

1. Let's remove the Aggregate data

- Let's try doing it with a mask (I will make group of what data I don't want to included, then with the ~ sign I'll remove it)

In [268]:
mask = HPI['Country_Raw'].str.contains('aggregate|economies|World|area', case=False)
HPI = HPI[~mask]

In [269]:
HPI

          Country_Raw     Quarter  Real Price Index
144        AT:Austria  2000-03-31           98.2843
145        AT:Austria  2000-06-30           95.9464
146        AT:Austria  2000-09-30           93.7325
147        AT:Austria  2000-12-31           92.7328
148        AT:Austria  2001-03-31           96.5591
...               ...         ...               ...
5750  ZA:South Africa  2024-12-31           87.9349
5751  ZA:South Africa  2025-03-31           87.9561
5752  ZA:South Africa  2025-06-30           88.0077
5753  ZA:South Africa  2025-09-30           88.3881
5754  ZA:South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

- Now I have to remove the country code

In [270]:
HPI['Country_Raw'].str.split(':').str[1]

144          Austria
145          Austria
146          Austria
147          Austria
148          Austria
            ...
5750    South Africa
5751    South Africa
5752    South Africa
5753    South Africa
5754    South Africa
Name: Country_Raw, Length: 5436, dtype: object

In [271]:
HPI.loc[:, 'Country'] = HPI['Country_Raw'].str.split(':').str[1]

In [272]:
HPI

          Country_Raw     Quarter  Real Price Index       Country
144        AT:Austria  2000-03-31           98.2843       Austria
145        AT:Austria  2000-06-30           95.9464       Austria
146        AT:Austria  2000-09-30           93.7325       Austria
147        AT:Austria  2000-12-31           92.7328       Austria
148        AT:Austria  2001-03-31           96.5591       Austria
...               ...         ...               ...           ...
5750  ZA:South Africa  2024-12-31           87.9349  South Africa
5751  ZA:South Africa  2025-03-31           87.9561  South Africa
5752  ZA:South Africa  2025-06-30           88.0077  South Africa
5753  ZA:South Africa  2025-09-30           88.3881  South Africa
5754  ZA:South Africa  2025-12-31           89.4681  South Africa

[5436 rows x 4 columns]

In [273]:
HPI_c = HPI[['Country', 'Quarter', 'Real Price Index']] # HPC_c= Housing Price index clean

In [274]:
HPI_c

           Country     Quarter  Real Price Index
144        Austria  2000-03-31           98.2843
145        Austria  2000-06-30           95.9464
146        Austria  2000-09-30           93.7325
147        Austria  2000-12-31           92.7328
148        Austria  2001-03-31           96.5591
...            ...         ...               ...
5750  South Africa  2024-12-31           87.9349
5751  South Africa  2025-03-31           87.9561
5752  South Africa  2025-06-30           88.0077
5753  South Africa  2025-09-30           88.3881
5754  South Africa  2025-12-31           89.4681

[5436 rows x 3 columns]

Now we have the clean version of the table - only contains clean country data

In [275]:
print(HPI_c['Country'].unique()) # I want to to see with which countries I'm working with and check which fall into what group

['Austria' 'Australia' 'Belgium' 'Bulgaria' 'Brazil' 'Canada'
 'Switzerland' 'Chile' 'China' 'Colombia' 'Cyprus' 'Czechia' 'Germany'
 'Denmark' 'Estonia' 'Spain' 'Finland' 'France' 'United Kingdom' 'Greece'
 'Hong Kong SAR' 'Croatia' 'Hungary' 'Indonesia' 'Ireland' 'Israel'
 'India' 'Iceland' 'Italy' 'Japan' 'Korea' 'Lithuania' 'Luxembourg'
 'Latvia' 'Morocco' 'North Macedonia' 'Malta' 'Mexico' 'Malaysia'
 'Netherlands' 'Norway' 'New Zealand' 'Peru' 'Philippines' 'Poland'
 'Portugal' 'Romania' 'Serbia' 'Russia' 'Sweden' 'Singapore' 'Slovenia'
 'Slovakia' 'Thailand' 'Türkiye' 'United States' 'South Africa']

Looking at the data, not all countries have data from 2000 onwards
The data is already in chronicological order so I won't be sorting it

I decide to look when is the first entry for each country to find an idea of when to start the data

In [276]:
first_entries = HPI_c.groupby('Country').first()
print(first_entries)

                    Quarter  Real Price Index
Country
Australia        2000-03-31           55.9766
Austria          2000-03-31           98.2843
Belgium          2000-03-31           66.7303
Brazil           2001-03-31           52.2932
Bulgaria         2000-03-31           59.6427
Canada           2000-03-31           60.0711
Chile            2002-03-31           73.3761
China            2005-06-30           87.9500
Colombia         2000-03-31           76.9397
Croatia          2000-03-31           74.2766
Cyprus           2002-03-31           55.2744
Czechia          2008-03-31          105.4167
Denmark          2000-03-31           72.6628
Estonia          2005-03-31          101.9719
Finland          2000-03-31           73.7069
France           2000-03-31           57.0587
Germany          2000-03-31          118.7491
Greece           2000-03-31           77.6642
Hong Kong SAR    2000-03-31           66.4739
Hungary          2000-03-31           82.1241
Iceland          2000-03-31           85.0683
India            2009-03-31           88.9013
Indonesia        2002-03-31          139.3968
Ireland          2000-03-31           94.4460
Israel           2000-03-31           92.3658
Italy            2000-03-31           76.3039
Japan            2000-03-31          141.4415
Korea            2000-03-31           82.5668
Latvia           2006-03-31          149.2465
Lithuania        2000-03-31           41.9676
Luxembourg       2007-03-31           97.3951
Malaysia         2000-03-31           86.2324
Malta            2005-03-31           70.9393
Mexico           2005-03-31           90.9971
Morocco          2007-03-31          102.5356
Netherlands      2000-03-31           84.0758
New Zealand      2000-03-31           62.5862
North Macedonia  2000-03-31           72.7104
Norway           2000-03-31           62.6810
Peru             2000-03-31           83.5080
Philippines      2008-03-31          107.8330
Poland           2010-03-31          100.0602
Portugal         2000-03-31          118.7076
Romania          2009-03-31          119.3204
Russia           2001-03-31           34.9443
Serbia           2000-03-31          135.2788
Singapore        2000-03-31           87.8241
Slovakia         2006-03-31           82.1598
Slovenia         2007-03-31          110.1683
South Africa     2000-03-31           56.8608
Spain            2000-03-31           59.2993
Sweden           2000-03-31           53.3734
Switzerland      2000-03-31           77.5257
Thailand         2000-03-31           96.8028
Türkiye          2010-03-31           98.6380
United Kingdom   2000-03-31           62.6002
United States    2000-03-31           95.1841

The latest start is 2010-03-31, so I will start from then

In [277]:
print(HPI_c['Quarter'].dtype)

object

To remove any data before 2010:

In [278]:
HPI_c = HPI_c[HPI_c['Quarter'] >= '2010-01-01'].copy()

In [279]:
HPI_c

           Country     Quarter  Real Price Index
184        Austria  2010-03-31          100.2528
185        Austria  2010-06-30           99.5266
186        Austria  2010-09-30           99.7640
187        Austria  2010-12-31          100.4564
188        Austria  2011-03-31          101.9770
...            ...         ...               ...
5750  South Africa  2024-12-31           87.9349
5751  South Africa  2025-03-31           87.9561
5752  South Africa  2025-06-30           88.0077
5753  South Africa  2025-09-30           88.3881
5754  South Africa  2025-12-31           89.4681

[3617 rows x 3 columns]

To check if I did it correctly

In [280]:
first_entries = HPI_c.groupby('Country').first()
print(first_entries)

                    Quarter  Real Price Index
Country
Australia        2010-03-31           99.9682
Austria          2010-03-31          100.2528
Belgium          2010-03-31           99.4178
Brazil           2010-03-31           93.9314
Bulgaria         2010-03-31          102.5328
Canada           2010-03-31          100.2438
Chile            2010-03-31           97.1334
China            2010-03-31           98.4735
Colombia         2010-03-31           97.9763
Croatia          2010-03-31          102.0834
Cyprus           2010-03-31          101.9884
Czechia          2010-03-31          100.4567
Denmark          2010-03-31           99.1487
Estonia          2010-03-31          100.4538
Finland          2010-03-31           99.6381
France           2010-03-31           97.5617
Germany          2010-03-31           99.1342
Greece           2010-03-31          106.2279
Hong Kong SAR    2010-03-31           93.4491
Hungary          2010-03-31          102.6162
Iceland          2010-03-31           99.2311
India            2010-03-31           96.2271
Indonesia        2010-03-31          101.1526
Ireland          2010-03-31          106.1786
Israel           2010-03-31           96.7735
Italy            2010-03-31           99.6538
Japan            2010-03-31           99.4510
Korea            2010-03-31          100.4909
Latvia           2010-03-31           98.8298
Lithuania        2010-03-31           99.1576
Luxembourg       2010-03-31          101.2382
Malaysia         2010-03-31           96.8586
Malta            2010-03-31          101.9142
Mexico           2010-03-31           98.8179
Morocco          2010-03-31          100.5363
Netherlands      2010-03-31          101.0173
New Zealand      2010-03-31          102.4238
North Macedonia  2010-03-31          100.5580
Norway           2010-03-31           97.8581
Peru             2010-03-31           95.7671
Philippines      2010-03-31           99.6264
Poland           2010-03-31          100.0602
Portugal         2010-03-31          101.6861
Romania          2010-03-31          106.3460
Russia           2010-03-31          101.6916
Serbia           2010-03-31           99.0219
Singapore        2010-03-31           95.7487
Slovakia         2010-03-31          101.2206
Slovenia         2010-03-31          101.6593
South Africa     2010-03-31          100.2246
Spain            2010-03-31          101.3059
Sweden           2010-03-31           98.6638
Switzerland      2010-03-31           98.3530
Thailand         2010-03-31           99.1453
Türkiye          2010-03-31           98.6380
United Kingdom   2010-03-31           99.7592
United States    2010-03-31          101.5333

In [281]:
HPI_c

           Country     Quarter  Real Price Index
184        Austria  2010-03-31          100.2528
185        Austria  2010-06-30           99.5266
186        Austria  2010-09-30           99.7640
187        Austria  2010-12-31          100.4564
188        Austria  2011-03-31          101.9770
...            ...         ...               ...
5750  South Africa  2024-12-31           87.9349
5751  South Africa  2025-03-31           87.9561
5752  South Africa  2025-06-30           88.0077
5753  South Africa  2025-09-30           88.3881
5754  South Africa  2025-12-31           89.4681

[3617 rows x 3 columns]

According to the IMF (International money fund), since 2010 Croatia has graduated to becoming a "Developed economy"
in 2024.
So should Croatia be considered an emerging or developed country?
Croatia will be considered as an "Emerging economy" as
The HPI is anchored to 2010
Croatia became a developed country in 2024, so for the majority of the time it behaved as an Emerging economy

Let's start grouping countries based on their status as of 2010:

In [282]:
developed_eco = [
    'Australia', 'Austria', 'Belgium', 'Canada', 'Denmark', 'Finland', 
    'France', 'Germany', 'Greece', 'Hong Kong SAR', 'Iceland', 'Ireland', 
    'Israel', 'Italy', 'Japan', 'Korea', 'Luxembourg', 'Netherlands', 
    'New Zealand', 'Norway', 'Portugal', 'Singapore', 'Spain', 'Sweden', 
    'Switzerland', 'United Kingdom', 'United States'
]

In [283]:
HPI_c['Economy_Type'] = HPI_c['Country'].apply(
        lambda x: 'Advanced' if x in developed_eco else 'Growing'
)

In [284]:
HPI_c

           Country     Quarter  Real Price Index Economy_Type
184        Austria  2010-03-31          100.2528     Advanced
185        Austria  2010-06-30           99.5266     Advanced
186        Austria  2010-09-30           99.7640     Advanced
187        Austria  2010-12-31          100.4564     Advanced
188        Austria  2011-03-31          101.9770     Advanced
...            ...         ...               ...          ...
5750  South Africa  2024-12-31           87.9349      Growing
5751  South Africa  2025-03-31           87.9561      Growing
5752  South Africa  2025-06-30           88.0077      Growing
5753  South Africa  2025-09-30           88.3881      Growing
5754  South Africa  2025-12-31           89.4681      Growing

[3617 rows x 4 columns]

In [285]:
HPI_grouped = HPI_c.groupby(['Quarter', 'Economy_Type'])['Real Price Index'].mean().reset_index()

In [286]:
HPI_grouped

        Quarter Economy_Type  Real Price Index
0    2010-03-31     Advanced         99.866985
1    2010-03-31      Growing         99.836633
2    2010-06-30     Advanced         99.986937
3    2010-06-30      Growing        100.016910
4    2010-09-30     Advanced        100.337519
..          ...          ...               ...
123  2025-06-30      Growing        136.566800
124  2025-09-30     Advanced        132.038170
125  2025-09-30      Growing        137.433153
126  2025-12-31     Advanced        138.770836
127  2025-12-31      Growing        134.501873

[128 rows x 3 columns]

# Data 2: The central Banks policy rates

The central Banks policy rates -  set tracks the evolution of policy rates across the world. The policy rate is an important instrument used by central banks to implement their monetary policy. The data DOES NOT ACCOUNT for inflation, so we will need to get the data for inflation next :$Real\ Rate = Nominal\ Policy\ Rate - Inflation\ Rate$

In [287]:
CB_rates = pd.read_csv("Central_bank_policy_rates.csv", skiprows=5)

In [288]:
CB_rates

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-01-31,F:Free,NaN,A:Normal value,9.50
1,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-02-28,F:Free,NaN,A:Normal value,9.50
2,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-03-31,F:Free,NaN,A:Normal value,9.50
3,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-04-30,F:Free,NaN,A:Normal value,9.50
4,"BIS,WS_CBPOL,1.0",M.AR,M:Monthly,AR:Argentina,Per cent per year,Units,2010-05-31,F:Free,NaN,A:Normal value,9.50
...,...,...,...,...,...,...,...,...,...,...,...
7113,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-08-31,F:Free,NaN,A:Normal value,7.00
7114,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-09-30,F:Free,NaN,A:Normal value,7.00
7115,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-10-31,F:Free,NaN,A:Normal value,7.00
7116,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-11-30,F:Free,NaN,A:Normal value,6.75
7117,"BIS,WS_CBPOL,1.0",M.ZA,M:Monthly,ZA:South Africa,Per cent per year,Units,2025-12-31,F:Free,NaN,A:Normal value,6.75

For my analysis I need only a few columns: Reference Area (Country), Period (Date) and Observation Value (Price)

In [341]:
needed_columns = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
CBPR_clean = CB_rates[needed_columns].copy()

In [342]:
CB_clean

          Country_Raw     Monthly  Nominal Price Index       Country
0        AR:Argentina  2010-01-31                 9.50     Argentina
1        AR:Argentina  2010-02-28                 9.50     Argentina
2        AR:Argentina  2010-03-31                 9.50     Argentina
3        AR:Argentina  2010-04-30                 9.50     Argentina
4        AR:Argentina  2010-05-31                 9.50     Argentina
...               ...         ...                  ...           ...
7113  ZA:South Africa  2025-08-31                 7.00  South Africa
7114  ZA:South Africa  2025-09-30                 7.00  South Africa
7115  ZA:South Africa  2025-10-31                 7.00  South Africa
7116  ZA:South Africa  2025-11-30                 6.75  South Africa
7117  ZA:South Africa  2025-12-31                 6.75  South Africa

[7118 rows x 4 columns]

Next, we need to rename the columns

In [343]:
CBPR_clean.columns = ['Country_Raw', 'Monthly', 'Rate']

In [344]:
CBPR_clean

          Country_Raw     Monthly  Rate
0        AR:Argentina  2010-01-31  9.50
1        AR:Argentina  2010-02-28  9.50
2        AR:Argentina  2010-03-31  9.50
3        AR:Argentina  2010-04-30  9.50
4        AR:Argentina  2010-05-31  9.50
...               ...         ...   ...
7113  ZA:South Africa  2025-08-31  7.00
7114  ZA:South Africa  2025-09-30  7.00
7115  ZA:South Africa  2025-10-31  7.00
7116  ZA:South Africa  2025-11-30  6.75
7117  ZA:South Africa  2025-12-31  6.75

[7118 rows x 3 columns]

We need to remove the country code

In [345]:
CBPR_clean['Country'] = CBPR_clean['Country_Raw'].str.split(':').str[1]

In [346]:
CBPR_clean

          Country_Raw     Monthly  Rate       Country
0        AR:Argentina  2010-01-31  9.50     Argentina
1        AR:Argentina  2010-02-28  9.50     Argentina
2        AR:Argentina  2010-03-31  9.50     Argentina
3        AR:Argentina  2010-04-30  9.50     Argentina
4        AR:Argentina  2010-05-31  9.50     Argentina
...               ...         ...   ...           ...
7113  ZA:South Africa  2025-08-31  7.00  South Africa
7114  ZA:South Africa  2025-09-30  7.00  South Africa
7115  ZA:South Africa  2025-10-31  7.00  South Africa
7116  ZA:South Africa  2025-11-30  6.75  South Africa
7117  ZA:South Africa  2025-12-31  6.75  South Africa

[7118 rows x 4 columns]

In [347]:
CBPR_clean = CBPR_clean[['Country', 'Monthly', 'Rate']].copy()

In [348]:
CBPR_clean

           Country     Monthly  Rate
0        Argentina  2010-01-31  9.50
1        Argentina  2010-02-28  9.50
2        Argentina  2010-03-31  9.50
3        Argentina  2010-04-30  9.50
4        Argentina  2010-05-31  9.50
...            ...         ...   ...
7113  South Africa  2025-08-31  7.00
7114  South Africa  2025-09-30  7.00
7115  South Africa  2025-10-31  7.00
7116  South Africa  2025-11-30  6.75
7117  South Africa  2025-12-31  6.75

[7118 rows x 3 columns]

Because the data is monthly for the interest rates, but quarterly for the house price index, I have to make a mean for every quarter

1. Check if the monthly data is an 'object' or 'datatime'

In [349]:
print(CBPR_clean['Monthly'].dtype)

object

In [350]:
CBPR_clean['Monthly'] = pd.to_datetime(CBPR_clean['Monthly'])

In [351]:
print(CBPR_clean['Monthly'].dtype)

datetime64[ns]

2. Now that is a datetime, I make the quarterly mean with the same quarters as the HPI table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

 - Add a new column that indicates which month is in which Quater

In [355]:
CBPR_clean.loc[:, 'temp_quater'] = CBPR_clean['Monthly'].dt.to_period('Q')

In [356]:
CBPR_clean

           Country    Monthly  Rate temp_quater
0        Argentina 2010-01-31  9.50      2010Q1
1        Argentina 2010-02-28  9.50      2010Q1
2        Argentina 2010-03-31  9.50      2010Q1
3        Argentina 2010-04-30  9.50      2010Q2
4        Argentina 2010-05-31  9.50      2010Q2
...            ...        ...   ...         ...
7113  South Africa 2025-08-31  7.00      2025Q3
7114  South Africa 2025-09-30  7.00      2025Q3
7115  South Africa 2025-10-31  7.00      2025Q4
7116  South Africa 2025-11-30  6.75      2025Q4
7117  South Africa 2025-12-31  6.75      2025Q4

[7118 rows x 4 columns]

- Remove the monthly column, leave onthe the temp_quarter one and have its value be the mean of the Q

In [358]:
CBPR_quarterly = CBPR_clean.groupby(['Country', 'temp_quater'])['Rate'].mean().reset_index()

In [359]:
CBPR_quarterly

            Country temp_quater      Rate
0         Argentina      2010Q1  9.500000
1         Argentina      2010Q2  9.500000
2         Argentina      2010Q3  9.500000
3         Argentina      2010Q4  9.500000
4         Argentina      2011Q1  9.500000
...             ...         ...       ...
2369  United States      2024Q4  4.625000
2370  United States      2025Q1  4.375000
2371  United States      2025Q2  4.375000
2372  United States      2025Q3  4.291667
2373  United States      2025Q4  3.791667

[2374 rows x 3 columns]

It stood out to me that in the last few tables the last entry was South Africa, but now is the USA

In [360]:
print(CBPR_quarterly['Country'].unique())

['Argentina' 'Australia' 'Brazil' 'Canada' 'Chile' 'China' 'Colombia'
 'Croatia' 'Czechia' 'Denmark' 'Euro area' 'Hong Kong SAR' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Israel' 'Japan' 'Korea' 'Kuwait'
 'Malaysia' 'Mexico' 'Morocco' 'New Zealand' 'North Macedonia' 'Norway'
 'Peru' 'Philippines' 'Poland' 'Romania' 'Russia' 'Saudi Arabia' 'Serbia'
 'South Africa' 'Sweden' 'Switzerland' 'Thailand' 'Türkiye'
 'United Kingdom' 'United States']

In [361]:
print(CBPR_clean['Country'].unique())

['Argentina' 'Australia' 'Brazil' 'Canada' 'Switzerland' 'Chile' 'China'
 'Colombia' 'Czechia' 'Denmark' 'United Kingdom' 'Hong Kong SAR' 'Croatia'
 'Hungary' 'Indonesia' 'Israel' 'India' 'Iceland' 'Japan' 'Korea' 'Kuwait'
 'Morocco' 'North Macedonia' 'Mexico' 'Malaysia' 'Norway' 'New Zealand'
 'Peru' 'Philippines' 'Poland' 'Romania' 'Serbia' 'Russia' 'Saudi Arabia'
 'Sweden' 'Thailand' 'Türkiye' 'United States' 'Euro area' 'South Africa']

In [362]:
print(CBPR_quarterly['Country'].nunique())

40

In [363]:
print(CBPR_clean['Country'].nunique())

40

- I don't need the 'Euro area' data so

In [364]:
CBPR_quarterly = CBPR_quarterly.loc[CBPR_quarterly['Country'] != 'Euro area']

In [365]:
print(CBPR_quarterly['Country'].nunique()) # Check if I removed the Euro area

39

- Make 2010Q1 to 2010-03-31

In [367]:
CBPR_quarterly = CBPR_quarterly.copy()
CBPR_quarterly.loc[:, 'Quarter'] = CBPR_quarterly['temp_quater'].dt.to_timestamp('Q')

In [368]:
CBPR_quarterly

            Country temp_quater      Rate    Quarter
0         Argentina      2010Q1  9.500000 2010-03-31
1         Argentina      2010Q2  9.500000 2010-06-30
2         Argentina      2010Q3  9.500000 2010-09-30
3         Argentina      2010Q4  9.500000 2010-12-31
4         Argentina      2011Q1  9.500000 2011-03-31
...             ...         ...       ...        ...
2369  United States      2024Q4  4.625000 2024-12-31
2370  United States      2025Q1  4.375000 2025-03-31
2371  United States      2025Q2  4.375000 2025-06-30
2372  United States      2025Q3  4.291667 2025-09-30
2373  United States      2025Q4  3.791667 2025-12-31

[2314 rows x 4 columns]

In [372]:
final_columns = ['Country', 'Quarter', 'Rate'] 
CBPR_final = CBPR_quarterly[final_columns]

In [373]:
CBPR_final

            Country    Quarter      Rate
0         Argentina 2010-03-31  9.500000
1         Argentina 2010-06-30  9.500000
2         Argentina 2010-09-30  9.500000
3         Argentina 2010-12-31  9.500000
4         Argentina 2011-03-31  9.500000
...             ...        ...       ...
2369  United States 2024-12-31  4.625000
2370  United States 2025-03-31  4.375000
2371  United States 2025-06-30  4.375000
2372  United States 2025-09-30  4.291667
2373  United States 2025-12-31  3.791667

[2314 rows x 3 columns]

# DATA 3: Consumer prices

The consumer price index data set contains long series that track the overall change in the prices of goods and services purchased by households. Consumer price indices are a key macroeconomic indicator, for instance to measure inflation and assess purchasing power over time.

In [50]:
Consumer_prices = pd.read_csv("Consumer_prices_Yearly_change.csv", skiprows=5)

In [51]:
Consumer_prices

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,REF_AREA:Reference area,UNIT_MEASURE:Unit of measure,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_LONG_CPI,1.0",M.AE.771,M:Monthly,AE:United Arab Emirates,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2010-01-31,F:Free,NaN,A:Normal value,-0.431897
1,"BIS,WS_LONG_CPI,1.0",M.AE.771,M:Monthly,AE:United Arab Emirates,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2010-02-28,F:Free,NaN,A:Normal value,-0.264243
2,"BIS,WS_LONG_CPI,1.0",M.AE.771,M:Monthly,AE:United Arab Emirates,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2010-03-31,F:Free,NaN,A:Normal value,0.682230
3,"BIS,WS_LONG_CPI,1.0",M.AE.771,M:Monthly,AE:United Arab Emirates,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2010-04-30,F:Free,NaN,A:Normal value,0.789923
4,"BIS,WS_LONG_CPI,1.0",M.AE.771,M:Monthly,AE:United Arab Emirates,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2010-05-31,F:Free,NaN,A:Normal value,0.876724
...,...,...,...,...,...,...,...,...,...,...,...,...
12086,"BIS,WS_LONG_CPI,1.0",M.ZA.771,M:Monthly,ZA:South Africa,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2025-08-31,F:Free,NaN,A:Normal value,3.303274
12087,"BIS,WS_LONG_CPI,1.0",M.ZA.771,M:Monthly,ZA:South Africa,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2025-09-30,F:Free,NaN,A:Normal value,3.399981
12088,"BIS,WS_LONG_CPI,1.0",M.ZA.771,M:Monthly,ZA:South Africa,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2025-10-31,F:Free,NaN,A:Normal value,3.603607
12089,"BIS,WS_LONG_CPI,1.0",M.ZA.771,M:Monthly,ZA:South Africa,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2025-11-30,F:Free,NaN,A:Normal value,3.503496
12090,"BIS,WS_LONG_CPI,1.0",M.ZA.771,M:Monthly,ZA:South Africa,"771:Year-on-year changes, in per cent","Year-on-year changes, in per cent",Units,2025-12-31,F:Free,NaN,A:Normal value,3.600003

Again, I will need only Country, Period and Value parts of the data

In [52]:
columns_needed = ['REF_AREA:Reference area', 'TIME_PERIOD:Period', 'OBS_VALUE:Value']
Consumer_prices = Consumer_prices[columns_needed]

In [53]:
Consumer_prices

       REF_AREA:Reference area TIME_PERIOD:Period  OBS_VALUE:Value
0      AE:United Arab Emirates         2010-01-31        -0.431897
1      AE:United Arab Emirates         2010-02-28        -0.264243
2      AE:United Arab Emirates         2010-03-31         0.682230
3      AE:United Arab Emirates         2010-04-30         0.789923
4      AE:United Arab Emirates         2010-05-31         0.876724
...                        ...                ...              ...
12086          ZA:South Africa         2025-08-31         3.303274
12087          ZA:South Africa         2025-09-30         3.399981
12088          ZA:South Africa         2025-10-31         3.603607
12089          ZA:South Africa         2025-11-30         3.503496
12090          ZA:South Africa         2025-12-31         3.600003

[12091 rows x 3 columns]

Let's rename the columns

In [54]:
Consumer_prices.columns = ['Country_Raw', 'Monthly', '% Change of Inflation']

In [55]:
Consumer_prices

                   Country_Raw     Monthly  % Change of Inflation
0      AE:United Arab Emirates  2010-01-31              -0.431897
1      AE:United Arab Emirates  2010-02-28              -0.264243
2      AE:United Arab Emirates  2010-03-31               0.682230
3      AE:United Arab Emirates  2010-04-30               0.789923
4      AE:United Arab Emirates  2010-05-31               0.876724
...                        ...         ...                    ...
12086          ZA:South Africa  2025-08-31               3.303274
12087          ZA:South Africa  2025-09-30               3.399981
12088          ZA:South Africa  2025-10-31               3.603607
12089          ZA:South Africa  2025-11-30               3.503496
12090          ZA:South Africa  2025-12-31               3.600003

[12091 rows x 3 columns]

The data for the consumer prices is monthly, but I need it in quarters

1. Check if the Monthly data is object or datetime

In [56]:
print(Consumer_prices['Monthly'].dtype)

object

2. It's an object so we change it to datetime

In [68]:
Consumer_prices.loc[:, 'Monthly'] = pd.to_datetime(Consumer_prices['Monthly'])

In [72]:
print(Consumer_prices['Monthly'].dtype)

datetime64[ns]

3. To match the other tables, I remove the country code

In [77]:
Consumer_prices.loc[:, 'Country'] = Consumer_prices['Country_Raw'].str.split(':').str[1]
CP_clean = Consumer_prices[['Country', 'Monthly', '% Change of Inflation']] # CP_clean= Consumer prices clean

In [78]:
CP_clean

                    Country    Monthly  % Change of Inflation
0      United Arab Emirates 2010-01-31              -0.431897
1      United Arab Emirates 2010-02-28              -0.264243
2      United Arab Emirates 2010-03-31               0.682230
3      United Arab Emirates 2010-04-30               0.789923
4      United Arab Emirates 2010-05-31               0.876724
...                     ...        ...                    ...
12086          South Africa 2025-08-31               3.303274
12087          South Africa 2025-09-30               3.399981
12088          South Africa 2025-10-31               3.603607
12089          South Africa 2025-11-30               3.503496
12090          South Africa 2025-12-31               3.600003

[12091 rows x 3 columns]

4. Now that is a datetime and countries are okay, I make the quarterly mean with the same quarters as the HPI & CBPR table (Year-03-31, Year-6-30, Year-9-30 and Year-12-31)

I insert a new column that indicates if the month belongs to Q1, Q2, Q3 or Q4

In [81]:
CP_clean.loc[:, 'temp_quater'] = Consumer_prices['Monthly'].dt.to_period('Q')

In [82]:
CP_clean

                    Country    Monthly  % Change of Inflation temp_quater
0      United Arab Emirates 2010-01-31              -0.431897      2010Q1
1      United Arab Emirates 2010-02-28              -0.264243      2010Q1
2      United Arab Emirates 2010-03-31               0.682230      2010Q1
3      United Arab Emirates 2010-04-30               0.789923      2010Q2
4      United Arab Emirates 2010-05-31               0.876724      2010Q2
...                     ...        ...                    ...         ...
12086          South Africa 2025-08-31               3.303274      2025Q3
12087          South Africa 2025-09-30               3.399981      2025Q3
12088          South Africa 2025-10-31               3.603607      2025Q4
12089          South Africa 2025-11-30               3.503496      2025Q4
12090          South Africa 2025-12-31               3.600003      2025Q4

[12091 rows x 4 columns]

In [83]:
CP_clean.loc[:, 'temp_quater'] = CP_clean['Monthly'].dt.to_period('Q')

In [84]:
CP_clean

                    Country    Monthly  % Change of Inflation temp_quater
0      United Arab Emirates 2010-01-31              -0.431897      2010Q1
1      United Arab Emirates 2010-02-28              -0.264243      2010Q1
2      United Arab Emirates 2010-03-31               0.682230      2010Q1
3      United Arab Emirates 2010-04-30               0.789923      2010Q2
4      United Arab Emirates 2010-05-31               0.876724      2010Q2
...                     ...        ...                    ...         ...
12086          South Africa 2025-08-31               3.303274      2025Q3
12087          South Africa 2025-09-30               3.399981      2025Q3
12088          South Africa 2025-10-31               3.603607      2025Q4
12089          South Africa 2025-11-30               3.503496      2025Q4
12090          South Africa 2025-12-31               3.600003      2025Q4

[12091 rows x 4 columns]

Now, I want to have the mean of the quaterters

In [85]:
CP_q = CP_clean.groupby(['Country', 'temp_quater'])['% Change of Inflation'].mean().reset_index()

In [86]:
CP_q

            Country temp_quater  % Change of Inflation
0           Algeria      2010Q1               4.323700
1           Algeria      2010Q2               4.946776
2           Algeria      2010Q3               3.465990
3           Algeria      2010Q4               2.989893
4           Algeria      2011Q1               3.495927
...             ...         ...                    ...
4027  United States      2024Q4               2.745114
4028  United States      2025Q1               2.737586
4029  United States      2025Q2               2.445133
4030  United States      2025Q3               2.877918
4031  United States      2025Q4               2.706082

[4032 rows x 3 columns]

Now, let's make the temp_quarter column to look like the others (YYYY-03-31)

In [87]:
CP_q.loc[:, 'Quarter'] = CP_q['temp_quater'].dt.to_timestamp('Q')
final_columns = ['Country', 'Quarter', '% Change of Inflation'] 
CP_final = CP_q[final_columns]

In [88]:
CP_final

            Country    Quarter  % Change of Inflation
0           Algeria 2010-03-31               4.323700
1           Algeria 2010-06-30               4.946776
2           Algeria 2010-09-30               3.465990
3           Algeria 2010-12-31               2.989893
4           Algeria 2011-03-31               3.495927
...             ...        ...                    ...
4027  United States 2024-12-31               2.745114
4028  United States 2025-03-31               2.737586
4029  United States 2025-06-30               2.445133
4030  United States 2025-09-30               2.877918
4031  United States 2025-12-31               2.706082

[4032 rows x 3 columns]